export interface Data {
  ko: string;
  en: string;
}

export const data: Data[] = [
  { ko: "하나의", en: "a" },
  { ko: "버리다", en: "abandon" },
  { ko: "할 수 있는", en: "able" },
  { ko: "배로", en: "aboard" },
  { ko: "유산하다", en: "abort" },
  { ko: "-에 대하여", en: "about" },
  { ko: "-보다 위에", en: "above" },
  { ko: "외국으로", en: "abroad" },
  { ko: "부재의", en: "absent" },
  { ko: "절대의", en: "absolute" },
  { ko: "흡수하다", en: "absorb" },
  { ko: "추상적인", en: "abstract" },
  { ko: "불합리한", en: "absurd" },
  { ko: "풍부한", en: "abundant" },
  { ko: "남용", en: "abuse" },
  { ko: "학술원", en: "academy" },
  { ko: "가속하다 속도가 가해지다", en: "accelerate" },
  { ko: "액센트", en: "accent" },
  { ko: "받아들이다", en: "accept" },
  { ko: "접근", en: "access" },
  { ko: "뜻밖의 사건", en: "accident" },
  { ko: "수용하다", en: "accommodate" },
  { ko: "동반하다", en: "accompany" },
  { ko: "이루다", en: "accomplish" },
  { ko: "일치하다", en: "accord" },
  { ko: "설명하다 계산", en: "account" },
  { ko: "축적하다", en: "accumulate" },
  { ko: "정확한", en: "accurate" },
  { ko: "고발하다", en: "accuse" },
  { ko: "성취하다", en: "achieve" },
  { ko: "산 신", en: "acid" },
  { ko: "인정하다", en: "acknowledge" },
  { ko: "알리다", en: "acquaint" },
  { ko: "얻다", en: "acquire" },
  { ko: "획득", en: "acquisition" },
  { ko: "가로질러", en: "across" },
  { ko: "vi행동하다", en: "act" },
  { ko: "활동적으로 하다", en: "activate" },
  { ko: "현실의", en: "actual" },
  { ko: "날카로운", en: "acute" },
  { ko: "적용시키다", en: "adapt" },
  { ko: "추가하다", en: "add" },
  { ko: "열중하게 하다", en: "addict" },
  { ko: "말을 걸다", en: "address" },
  { ko: "충분한", en: "adequate" },
  { ko: "맞추다", en: "adjust" },
  { ko: "관리하다", en: "administer" },
  { ko: "감복하다", en: "admire" },
  { ko: "입장", en: "admission" },
  { ko: "받아들이다", en: "admit" },
  { ko: "청년기의", en: "adolescent" },
  { ko: "채용하다", en: "adopt" },
  { ko: "성인", en: "adult" },
  { ko: "나아가다", en: "advance" },
  { ko: "유리한 입장", en: "advantage" },
  { ko: "모험 모험하다", en: "adventure" },
  { ko: "거꾸로의", en: "adverse" },
  { ko: "광고하다", en: "advertize" },
  { ko: "충고하다", en: "advise" },
  { ko: "변호사", en: "advocate" },
  { ko: "미적인", en: "aesthetic" },
  { ko: "일", en: "affair" },
  { ko: "영향을 주다", en: "affect" },
  { ko: "애정", en: "affection" },
  { ko: "회원으로 가입시키다", en: "affiliate" },
  { ko: "여유가 있다", en: "afford" },
  { ko: "두려워하여", en: "afraid" },
  { ko: "후에", en: "after" },
  { ko: "오후", en: "afternoon" },
  { ko: "다시", en: "again" },
  { ko: "…에 반대하여", en: "against" },
  { ko: "연령", en: "age" },
  { ko: "기능", en: "agency" },
  { ko: "안건", en: "agenda" },
  { ko: "대리인", en: "agent" },
  { ko: "침략적인", en: "aggressive" },
  { ko: "이전에", en: "ago" },
  { ko: "동의하다", en: "agree" },
  { ko: "농업", en: "agriculture" },
  { ko: "전방에", en: "ahead" },
  { ko: "도와 주다", en: "aid" },
  { ko: "겨누다", en: "aim" },
  { ko: "공기", en: "air" },
  { ko: "비행기", en: "airplane" },
  { ko: "항공기", en: "aircraft" },
  { ko: "정기항공", en: "airline" },
  { ko: "공항", en: "airport" },
  { ko: "측면복도", en: "aisle" },
  { ko: "빈틈없는", en: "alert" },
  { ko: "외국의", en: "alien" },
  { ko: "비슷한", en: "alike" },
  { ko: "살아있는", en: "alive" },
  { ko: "모든", en: "all" },
  { ko: "할당하다", en: "allocate" },
  { ko: "허락하다", en: "allow" },
  { ko: "동맹하다", en: "ally" },
  { ko: "거의", en: "almost" },
  { ko: "다만 홀로(혼자서)", en: "alone" },
  { ko: "-을 따라", en: "along" },
  { ko: "-의 곁에", en: "alongside" },
  { ko: "큰 소리로", en: "aloud" },
  { ko: "이미", en: "already" },
  { ko: "더할나위없이", en: "alright" },
  { ko: "-도 또한", en: "also" },
  { ko: "바꾸다", en: "alter" },
  { ko: "어느 한쪽의 양자택일", en: "alternative" },
  { ko: "비록 -일지라도", en: "although" },
  { ko: "전혀", en: "altogether" },
  { ko: "늘", en: "always" },
  { ko: "오전", en: "A.M." },
  { ko: "깜짝 놀라게 하다", en: "amaze" },
  { ko: "대사", en: "ambassador" },
  { ko: "야심", en: "ambition" },
  { ko: "-중에", en: "among" },
  { ko: "(금액이)-이 되다", en: "amount" },
  { ko: "확대하다", en: "amplify" },
  { ko: "재미나게 하다", en: "amuse" },
  { ko: "분해하다", en: "analyze" },
  { ko: "닻", en: "anchor" },
  { ko: "옛날의", en: "ancient" },
  { ko: "및", en: "and" },
  { ko: "천사", en: "angel" },
  { ko: "성", en: "anger" },
  { ko: "각", en: "angle" },
  { ko: "동물", en: "animal" },
  { ko: "기념일 예년의", en: "anniversary" },
  { ko: "알리다", en: "announce" },
  { ko: "귀찮게하다", en: "annoy" },
  { ko: "일년의", en: "annual" },
  { ko: "또 하나", en: "another" },
  { ko: "대답", en: "answer" },
  { ko: "개미", en: "ant" },
  { ko: "예기하다", en: "anticipate" },
  { ko: "근심", en: "anxiety" },
  { ko: "걱정되는", en: "anxious" },
  { ko: "어떤", en: "any" },
  { ko: "떨어져서", en: "apart" },
  { ko: "사과", en: "apology" },
  { ko: "명백한", en: "apparent" },
  { ko: "간청하다", en: "appeal" },
  { ko: "나타나다", en: "appear" },
  { ko: "사과", en: "apple" },
  { ko: "지원자", en: "applicant" },
  { ko: "(물건을)대다", en: "apply" },
  { ko: "지정하다", en: "appoint" },
  { ko: "감상하다", en: "appreciate" },
  { ko: "다가가다", en: "approach" },
  { ko: "적당한", en: "appropriate" },
  { ko: "시인하다", en: "approve" },
  { ko: "어림셈의", en: "approximate" },
  { ko: "건축가", en: "architect" },
  { ko: "건축", en: "architecture" },
  { ko: "기록보관소", en: "archive" },
  { ko: "면적", en: "area" },
  { ko: "논하다", en: "argue" },
  { ko: "생기다", en: "arise" },
  { ko: "팔", en: "arm" },
  { ko: "육군", en: "army" },
  { ko: "사방에", en: "around" },
  { ko: "가지런히 하다", en: "arrange" },
  { ko: "체포하다", en: "arrest" },
  { ko: "도착하다", en: "arrive" },
  { ko: "화살", en: "arrow" },
  { ko: "예술", en: "art" },
  { ko: "물품", en: "article" },
  { ko: "인공의", en: "artificial" },
  { ko: "-와 같은 정도로", en: "as" },
  { ko: "회", en: "ash" },
  { ko: "곁에", en: "aside" },
  { ko: "묻다", en: "ask" },
  { ko: "잠들은", en: "asleep" },
  { ko: "관점", en: "aspect" },
  { ko: "열망하다", en: "aspire" },
  { ko: "습격", en: "assault" },
  { ko: "모으다", en: "assemble" },
  { ko: "단언하다", en: "assert" },
  { ko: "(세금 등을)사정하다", en: "assess" },
  { ko: "자산", en: "asset" },
  { ko: "할당하다", en: "assign" },
  { ko: "돕다", en: "assist" },
  { ko: "연상하다", en: "associate" },
  { ko: "취하다", en: "assume" },
  { ko: "보증하다", en: "assure" },
  { ko: "놀라게 하다", en: "astonish" },
  { ko: "-에서", en: "at" },
  { ko: "운동가", en: "athlete" },
  { ko: "대기", en: "atmosphere" },
  { ko: "원자", en: "atom" },
  { ko: "붙이다", en: "attach" },
  { ko: "공격하다", en: "attack" },
  { ko: "이르다", en: "attain" },
  { ko: "시도하다", en: "attempt" },
  { ko: "출석하다", en: "attend" },
  { ko: "주의", en: "attention" },
  { ko: "태도", en: "attitude" },
  { ko: "변호사", en: "attorney" },
  { ko: "끌어 당기다", en: "attract" },
  { ko: "속성", en: "attribute" },
  { ko: "경매", en: "auction" },
  { ko: "청중", en: "audience" },
  { ko: "아주머니", en: "aunt" },
  { ko: "진짜의", en: "authentic" },
  { ko: "저자", en: "author" },
  { ko: "자서전", en: "autobiography" },
  { ko: "자동의", en: "automatic" },
  { ko: "자동차 자동차의", en: "automobile" },
  { ko: "쓸모있는", en: "available" },
  { ko: "가로수길", en: "avenue" },
  { ko: "평균", en: "average" },
  { ko: "피하다", en: "avoid" },
  { ko: "기다리다", en: "await" },
  { ko: "깨우다", en: "awake" },
  { ko: "상", en: "award" },
  { ko: "알고 있는", en: "aware" },
  { ko: "떨어져서", en: "away" },
  { ko: "무서운", en: "awesome" },
  { ko: "두려운", en: "awful" },
  { ko: "어색한", en: "awkward" },
  { ko: '"갓난아이', en: "baby" },
  { ko: "등", en: "back" },
  { ko: "배경", en: "background" },
  { ko: "나쁜", en: "bad" },
  { ko: "굽다", en: "bake" },
  { ko: "균형", en: "balance" },
  { ko: "공", en: "ball" },
  { ko: "기구", en: "balloon" },
  { ko: "금지", en: "ban" },
  { ko: "그룹", en: "band" },
  { ko: "강타", en: "bang" },
  { ko: "둑", en: "bank" },
  { ko: "파산자", en: "bankrupt" },
  { ko: "막대기", en: "bar" },
  { ko: "벌거벗은", en: "bare" },
  { ko: "매매", en: "bargain" },
  { ko: "짖다", en: "bark" },
  { ko: "헛간", en: "barn" },
  { ko: "장벽", en: "barrier" },
  { ko: "기초", en: "base" },
  { ko: "야구", en: "baseball" },
  { ko: "기본의", en: "basic" },
  { ko: "기초", en: "basis" },
  { ko: "바구니", en: "basket" },
  { ko: "농구", en: "basketball" },
  { ko: "배트", en: "bat" },
  { ko: "목욕", en: "bath" },
  { ko: "욕실", en: "bathroom" },
  { ko: "전지", en: "battery" },
  { ko: "전투", en: "battle" },
  { ko: "만", en: "bay" },
  { ko: "-이다", en: "be" },
  { ko: "해안", en: "beach" },
  { ko: "광선", en: "beam" },
  { ko: "콩", en: "bean" },
  { ko: "나르다", en: "bear" },
  { ko: "턱수염", en: "beard" },
  { ko: "짐승", en: "beast" },
  { ko: "치다", en: "beat" },
  { ko: "아름다움", en: "beauty" },
  { ko: "왜냐하면", en: "because" },
  { ko: "-이 되다", en: "become" },
  { ko: "침대", en: "bed" },
  { ko: "침실 성적인", en: "bedroom" },
  { ko: "꿀벌", en: "bee" },
  { ko: "쇠고기", en: "beef" },
  { ko: "맥주", en: "beer" },
  { ko: "앞에", en: "before" },
  { ko: "청하다", en: "beg" },
  { ko: "시작하다", en: "begin" },
  { ko: "위함", en: "behalf" },
  { ko: "행동하다", en: "behave" },
  { ko: "행동", en: "behavior" },
  { ko: "뒤에", en: "behind" },
  { ko: "믿다", en: "believe" },
  { ko: "종", en: "bell" },
  { ko: "속하다", en: "belong" },
  { ko: "아래에", en: "below" },
  { ko: "구부리다", en: "bend" },
  { ko: "-의 바로 아래에", en: "beneath" },
  { ko: "이익", en: "benefit" },
  { ko: "액과", en: "berry" },
  { ko: "-의 곁에", en: "beside" },
  { ko: "걸다", en: "bet" },
  { ko: "배반하다", en: "betray" },
  { ko: "-의 사이에 사이에", en: "between" },
  { ko: "저편에", en: "beyond" },
  { ko: "치우침", en: "bias" },
  { ko: '"성서', en: "bible" },
  { ko: "자전거 자전거를 타다", en: "bicycle" },
  { ko: "큰", en: "big" },
  { ko: "계산서", en: "bill" },
  { ko: "10억", en: "billion" },
  { ko: "궤", en: "bin" },
  { ko: "매다", en: "bind" },
  { ko: "전기", en: "biography" },
  { ko: "생물학", en: "biology" },
  { ko: "새", en: "bird" },
  { ko: "출생", en: "birth" },
  { ko: "생일", en: "birthday" },
  { ko: "주교", en: "bishop" },
  { ko: "bite의 과거(분사) 작은 조각", en: "bit" },
  { ko: "물다", en: "bite" },
  { ko: "쓴", en: "bitter" },
  { ko: "검은", en: "black" },
  { ko: "책망하다", en: "blame" },
  { ko: "공백", en: "blank" },
  { ko: "담요", en: "blanket" },
  { ko: "돌풍", en: "blast" },
  { ko: "혼합하다", en: "blend" },
  { ko: "축복하다", en: "bless" },
  { ko: "눈먼", en: "blind" },
  { ko: "(눈을)깜빡거리다", en: "blink" },
  { ko: "덩어리", en: "block" },
  { ko: "(살결이 흰)금발의 여성", en: "blonde" },
  { ko: "피", en: "blood" },
  { ko: "쇳덩이", en: "bloom" },
  { ko: "(과수의)꽃", en: "blossom" },
  { ko: "강타", en: "blow" },
  { ko: "푸른", en: "blue" },
  { ko: "널빤지", en: "board" },
  { ko: "배", en: "boat" },
  { ko: "신체", en: "body" },
  { ko: "끓다", en: "boil" },
  { ko: "대담한", en: "bold" },
  { ko: "폭탄 폭격하다", en: "bomb" },
  { ko: "결속", en: "bond" },
  { ko: "뼈", en: "bone" },
  { ko: "책", en: "book" },
  { ko: "굉음", en: "boom" },
  { ko: "뒤를 밀기", en: "boost" },
  { ko: "목이 긴 구두", en: "boot" },
  { ko: "가장자리", en: "border" },
  { ko: "고조", en: "bore" },
  { ko: "빌다", en: "borrow" },
  { ko: "두목", en: "boss" },
  { ko: "쌍방의", en: "both" },
  { ko: "괴롭히다 근심하다 귀찮음", en: "bother" },
  { ko: "병", en: "bottle" },
  { ko: "밑바닥", en: "bottom" },
  { ko: "뛰어오르다", en: "bounce" },
  { ko: "경계", en: "boundary" },
  { ko: "절", en: "bow" },
  { ko: "사발", en: "bowl" },
  { ko: "소년", en: "boy" },
  { ko: "뇌", en: "brain" },
  { ko: "브레이크", en: "brake" },
  { ko: "가지", en: "branch" },
  { ko: "상표", en: "brand" },
  { ko: "용감한", en: "brave" },
  { ko: "빵", en: "bread" },
  { ko: "부수다", en: "break" },
  { ko: "아침밥", en: "breakfast" },
  { ko: "가슴", en: "breast" },
  { ko: "숨쉬다", en: "breathe" },
  { ko: "기르다", en: "breed" },
  { ko: "미풍", en: "breeze" },
  { ko: "양조하다", en: "brew" },
  { ko: "벽돌", en: "brick" },
  { ko: "신부", en: "bride" },
  { ko: "다리", en: "bridge" },
  { ko: "단시간의", en: "brief" },
  { ko: "밝은", en: "bright" },
  { ko: "빛나는", en: "brilliant" },
  { ko: "가져오다", en: "bring" },
  { ko: "(폭이)넓은", en: "broad" },
  { ko: "방송하다", en: "broadcast" },
  { ko: "형제", en: "brother" },
  { ko: "갈색의 갈색", en: "brown" },
  { ko: "솔", en: "brush" },
  { ko: "야수 짐승같은", en: "brute" },
  { ko: "거품 거품이 일다", en: "bubble" },
  { ko: "예산", en: "budget" },
  { ko: "벌레", en: "bug" },
  { ko: "짓다", en: "build" },
  { ko: "부피", en: "bulk" },
  { ko: "황소", en: "bull" },
  { ko: "탄환", en: "bullet" },
  { ko: "약한 자를 못살게 구는 자", en: "bully" },
  { ko: "충돌 부딪치다", en: "bump" },
  { ko: "송이", en: "bunch" },
  { ko: "다발", en: "bundle" },
  { ko: "후렴", en: "burden" },
  { ko: "시내", en: "burn" },
  { ko: "파열하다", en: "burst" },
  { ko: "묻다", en: "bury" },
  { ko: "덤불", en: "bush" },
  { ko: "직업", en: "business" },
  { ko: "바쁜", en: "busy" },
  { ko: "그러나 다만 (-을)제외하고", en: "but" },
  { ko: "정육점주인", en: "butcher" },
  { ko: "단추 단추를 채우다 단추로 채워지다", en: "button" },
  { ko: "사다", en: "buy" },
  { ko: "윙윙거리는 소리", en: "buzz" },
  { ko: "곁에", en: "by" },
  { ko: "택시", en: "cab" },
  { ko: "선실", en: "cabin" },
  { ko: "해저전신", en: "cable" },
  { ko: "새장", en: "cage" },
  { ko: "계산하다", en: "calculate" },
  { ko: "달력", en: "calendar" },
  { ko: "부르다", en: "call" },
  { ko: "평온한", en: "calm" },
  { ko: "au-할 수 있다", en: "can" },
  { ko: "취소하다", en: "cancel" },
  { ko: "암", en: "cancer" },
  { ko: "지원자", en: "candidate" },
  { ko: "사탕과자", en: "candy" },
  { ko: "돛베", en: "canvas" },
  { ko: "모자", en: "cap" },
  { ko: "할 수 있는", en: "capable" },
  { ko: "곶", en: "cape" },
  { ko: "수위의", en: "capital" },
  { ko: "우두머리(chief)", en: "captain" },
  { ko: "표제", en: "caption" },
  { ko: "붙잡다(=catch)", en: "capture" },
  { ko: "자동차", en: "car" },
  { ko: "걱정", en: "care" },
  { ko: "경력", en: "career" },
  { ko: "당근", en: "carrot" },
  { ko: "나르다", en: "carry" },
  { ko: "(2륜)짐마차", en: "cart" },
  { ko: "조각하다", en: "carve" },
  { ko: "경우", en: "case" },
  { ko: "현금 현금으로 바꾸다 현금의", en: "cash" },
  { ko: "던지다", en: "cast" },
  { ko: "성", en: "castle" },
  { ko: "우연한", en: "casual" },
  { ko: "고양이", en: "cat" },
  { ko: "붙잡다", en: "catch" },
  { ko: "범주", en: "category" },
  { ko: "음식물을 마련하다", en: "cater" },
  { ko: "대성당", en: "cathedral" },
  { ko: "소", en: "cattle" },
  { ko: "원인의", en: "causal" },
  { ko: "원인", en: "cause" },
  { ko: "조심", en: "caution" },
  { ko: "동굴 굴을 파다 꺼지다", en: "cave" },
  { ko: "그만두다 그치다 중지", en: "cease" },
  { ko: "천장", en: "ceiling" },
  { ko: "경축하다", en: "celebrate" },
  { ko: "명성", en: "celebrity" },
  { ko: "작은 방", en: "cell" },
  { ko: "검열관", en: "censor" },
  { ko: "1세기", en: "century" },
  { ko: "확신하는", en: "certain" },
  { ko: "증명서", en: "certificate" },
  { ko: "사슬", en: "chain" },
  { ko: "의장", en: "chair" },
  { ko: "의장", en: "chairman" },
  { ko: "도전", en: "challenge" },
  { ko: "방", en: "chamber" },
  { ko: "우연", en: "chance" },
  { ko: "변화", en: "change" },
  { ko: "혼돈", en: "chaos" },
  { ko: "인격", en: "character" },
  { ko: "특유한", en: "characteristic" },
  { ko: "요금", en: "charge" },
  { ko: "자비", en: "charity" },
  { ko: "매력", en: "charm" },
  { ko: "쫓다", en: "chase" },
  { ko: "잡담", en: "chat" },
  { ko: "값싼", en: "cheap" },
  { ko: "방해", en: "check" },
  { ko: "볼", en: "cheek" },
  { ko: "갈채", en: "cheer" },
  { ko: "쿡", en: "chef" },
  { ko: "화학의", en: "chemical" },
  { ko: "화학", en: "chemistry" },
  { ko: "가슴팍", en: "chest" },
  { ko: "씹다", en: "chew" },
  { ko: "우두머리", en: "chief" },
  { ko: "아이", en: "child" },
  { ko: "차가움", en: "chill" },
  { ko: "턱(끝) 턱에 대다", en: "chin" },
  { ko: "(나무)토막", en: "chip" },
  { ko: "(교회의)성가대", en: "choir" },
  { ko: "고르다", en: "choose" },
  { ko: "(도끼 등으로)자르다", en: "chop" },
  { ko: "합창", en: "chorus" },
  { ko: "만성의", en: "chronic" },
  { ko: "교회", en: "church" },
  { ko: "궐련", en: "cigarette" },
  { ko: "영화관", en: "cinema" },
  { ko: "원", en: "circle" },
  { ko: "순환하다", en: "circulate" },
  { ko: "환경", en: "circumstance" },
  { ko: "인용하다(quote)", en: "cite" },
  { ko: "시민", en: "citizen" },
  { ko: "도시", en: "city" },
  { ko: "시민의", en: "civil" },
  { ko: "요구하다", en: "claim" },
  { ko: "짝짝", en: "clap" },
  { ko: "맑게 하다", en: "clarify" },
  { ko: "충돌하다", en: "clash" },
  { ko: "계급", en: "class" },
  { ko: "고전의", en: "classic" },
  { ko: "분류하다", en: "classify" },
  { ko: "교실", en: "classroom" },
  { ko: "조항", en: "clause" },
  { ko: "찰흙", en: "clay" },
  { ko: "청결한", en: "clean" },
  { ko: "맑은", en: "clear" },
  { ko: "서기", en: "clerk" },
  { ko: "영리한", en: "clever" },
  { ko: "소송의뢰인", en: "client" },
  { ko: "절벽", en: "cliff" },
  { ko: "기후", en: "climate" },
  { ko: "기어 오르다", en: "climb" },
  { ko: "밀착하다", en: "cling" },
  { ko: "병원", en: "clinic" },
  { ko: "가위로 자르다", en: "clip" },
  { ko: "시계", en: "clock" },
  { ko: "닫다", en: "close" },
  { ko: "천", en: "cloth" },
  { ko: "구름", en: "cloud" },
  { ko: "클럽", en: "club" },
  { ko: "단서", en: "clue" },
  { ko: "떼", en: "cluster" },
  { ko: "역마차", en: "coach" },
  { ko: "석탄", en: "coal" },
  { ko: "연안", en: "coast" },
  { ko: "법전", en: "code" },
  { ko: "화폐", en: "coin" },
  { ko: "일치하다", en: "coincide" },
  { ko: "추운", en: "cold" },
  { ko: "공동으로 일하다", en: "collaborate" },
  { ko: "붕괴", en: "collapse" },
  { ko: "칼라", en: "collar" },
  { ko: "동료", en: "colleague" },
  { ko: "모으다", en: "collect" },
  { ko: "단과대학", en: "college" },
  { ko: "식민지", en: "colony" },
  { ko: "착색하다", en: "color" },
  { ko: "(신문 등의)난", en: "column" },
  { ko: "격투하다", en: "combat" },
  { ko: "결합하다", en: "combine" },
  { ko: "오다", en: "come" },
  { ko: "희극", en: "comedy" },
  { ko: "위안", en: "comfort" },
  { ko: "명령하다", en: "command" },
  { ko: "시작하다", en: "commence" },
  { ko: "논평", en: "comment" },
  { ko: "상업", en: "commerce" },
  { ko: "위임", en: "commission" },
  { ko: "위탁하다", en: "commit" },
  { ko: "위원회", en: "committee" },
  { ko: "상품", en: "commodity" },
  { ko: "알리다", en: "communicate" },
  { ko: "공산주의자", en: "communist" },
  { ko: "공동생활체", en: "community" },
  { ko: "동료", en: "companion" },
  { ko: "교제", en: "company" },
  { ko: "비교하다", en: "compare" },
  { ko: "양립할 수 있는", en: "compatible" },
  { ko: "억지로 -시키다", en: "compel" },
  { ko: "배상하다", en: "compensate" },
  { ko: "경쟁하다", en: "compete" },
  { ko: "능력있는", en: "competent" },
  { ko: "편찬하다", en: "compile" },
  { ko: "불평하다", en: "complain" },
  { ko: "보완하는 것", en: "complement" },
  { ko: "완성하다", en: "complete" },
  { ko: "합성물", en: "complex" },
  { ko: "복잡하게 하다", en: "complicate" },
  { ko: "구성하는 성분", en: "component" },
  { ko: "구성하다", en: "compose" },
  { ko: "성분 등을 혼합하다", en: "compound" },
  { ko: "이해력있는", en: "comprehensive" },
  { ko: "포함하다", en: "comprise" },
  { ko: "타협 타협하다", en: "compromise" },
  { ko: "의무적인", en: "compulsory" },
  { ko: "숨기다", en: "conceal" },
  { ko: "상상하다", en: "conceive" },
  { ko: "집중하다", en: "concentrate" },
  { ko: "개념", en: "concept" },
  { ko: "관계하다", en: "concern" },
  { ko: "연주회", en: "concert" },
  { ko: "결정하다", en: "conclude" },
  { ko: "구체적인 응고물", en: "concrete" },
  { ko: "나무라다", en: "condemn" },
  { ko: "조건", en: "condition" },
  { ko: "행위 이끌다", en: "conduct" },
  { ko: "주다", en: "confer" },
  { ko: "실토하다", en: "confess" },
  { ko: "확신하는", en: "confident" },
  { ko: "국경", en: "confine" },
  { ko: "확인하다", en: "confirm" },
  { ko: "투쟁", en: "conflict" },
  { ko: "일치시키다", en: "conform" },
  { ko: "직면하다", en: "confront" },
  { ko: "혼란시키다", en: "confuse" },
  { ko: "축하하다", en: "congratulate" },
  { ko: "회의", en: "congress" },
  { ko: "잇다 이어지다", en: "connect" },
  { ko: "양심", en: "conscience" },
  { ko: "의식적인", en: "conscious" },
  { ko: "(의견 등의)일치", en: "consensus" },
  { ko: "승낙하다", en: "consent" },
  { ko: "보존하다", en: "conserve" },
  { ko: "숙고하다", en: "consider" },
  { ko: "-으로 이루어지다", en: "consist" },
  { ko: "시종일관한", en: "consistent" },
  { ko: "불변의", en: "constant" },
  { ko: "구성하다", en: "constitute" },
  { ko: "강제하다", en: "constrain" },
  { ko: "건조하다", en: "construct" },
  { ko: "상의하다", en: "consult" },
  { ko: "소비하다", en: "consume" },
  { ko: "접촉", en: "contact" },
  { ko: "내포하다", en: "contain" },
  { ko: "현대의", en: "contemporary" },
  { ko: "싸우다", en: "contend" },
  { ko: "만족하여", en: "content" },
  { ko: "겨루다", en: "contest" },
  { ko: "문맥", en: "context" },
  { ko: "자제심이 있는", en: "continent" },
  { ko: "계속하다", en: "continue" },
  { ko: "계약", en: "contract" },
  { ko: "반박하다", en: "contradict" },
  { ko: "반대의 반대 거꾸로", en: "contrary" },
  { ko: "대조", en: "contrast" },
  { ko: "기부하다", en: "contribute" },
  { ko: "억제하다", en: "control" },
  { ko: "논쟁", en: "controversy" },
  { ko: "편리한", en: "convenient" },
  { ko: "관례", en: "convention" },
  { ko: "회화", en: "conversation" },
  { ko: "바꾸다", en: "convert" },
  { ko: "나르다", en: "convey" },
  { ko: "유죄로 판결하다 죄수", en: "convict" },
  { ko: "확신시키다", en: "convince" },
  { ko: "요리하다 요리사", en: "cook" },
  { ko: "쿠키", en: "cookie" },
  { ko: "서늘한", en: "cool" },
  { ko: "협동하다", en: "cooperate" },
  { ko: "동격의", en: "coordinate" },
  { ko: "순경", en: "cop" },
  { ko: "코우프(성직자의 긴 겉옷)", en: "cope" },
  { ko: "사본", en: "copy" },
  { ko: "판권", en: "copyright" },
  { ko: "밧줄", en: "cord" },
  { ko: "핵심", en: "core" },
  { ko: "티눈", en: "corn" },
  { ko: "모퉁이", en: "corner" },
  { ko: "법인조직의", en: "corporate" },
  { ko: "옳은", en: "correct" },
  { ko: "일치하다", en: "correspond" },
  { ko: "복도", en: "corridor" },
  { ko: "타락한", en: "corrupt" },
  { ko: "가격", en: "cost" },
  { ko: "복장", en: "costume" },
  { ko: "시골집", en: "cottage" },
  { ko: "목화", en: "cotton" },
  { ko: "침대", en: "couch" },
  { ko: "기침 기침을 하다 기침을 하여 -을 뱉어내다", en: "cough" },
  { ko: "aucan의 과거", en: "could" },
  { ko: "회의", en: "council" },
  { ko: "의논", en: "counsel" },
  { ko: "계산", en: "count" },
  { ko: "계산하는 사람", en: "counter" },
  { ko: "부본", en: "counterpart" },
  { ko: "나라", en: "country" },
  { ko: "시골", en: "countryside" },
  { ko: "주", en: "county" },
  { ko: "한 쌍", en: "couple" },
  { ko: "용기", en: "courage" },
  { ko: "사촌", en: "cousin" },
  { ko: "덮다", en: "cover" },
  { ko: "위협하다 암소", en: "cow" },
  { ko: "목동", en: "cowboy" },
  { ko: "찰싹 소리내다 금가다 날카로운소리", en: "crack" },
  { ko: "솜씨", en: "craft" },
  { ko: "도산", en: "crash" },
  { ko: "네발로 기다", en: "crawl" },
  { ko: "미친", en: "crazy" },
  { ko: "창조하다", en: "create" },
  { ko: "창조물", en: "creature" },
  { ko: "믿을 수 있는", en: "credible" },
  { ko: "신용", en: "credit" },
  { ko: "시내", en: "creek" },
  { ko: "기다", en: "creep" },
  { ko: "승무원", en: "crew" },
  { ko: "크리켓", en: "cricket" },
  { ko: "범죄", en: "crime" },
  { ko: "죄의", en: "criminal" },
  { ko: "위기", en: "crisis" },
  { ko: "파삭파삭한", en: "crisp" },
  { ko: "criterion의 복수형", en: "criteria" },
  { ko: "비평가", en: "critic" },
  { ko: "비평하다", en: "criticize" },
  { ko: "비평", en: "criticism" },
  { ko: "수확", en: "crop" },
  { ko: "십자형", en: "cross" },
  { ko: "군중", en: "crowd" },
  { ko: "왕관", en: "crown" },
  { ko: "결정적인", en: "crucial" },
  { ko: "잔인한", en: "cruel" },
  { ko: "순항하다", en: "cruise" },
  { ko: "눌러 부수다", en: "crush" },
  { ko: "소리치다", en: "cry" },
  { ko: "수정", en: "crystal" },
  { ko: "경작하다", en: "cultivate" },
  { ko: "문화", en: "culture" },
  { ko: "찬장", en: "cupboard" },
  { ko: "치료", en: "cure" },
  { ko: "이상스러운", en: "curious" },
  { ko: "곱슬머리 머리털을 지지다", en: "curl" },
  { ko: "통용", en: "currency" },
  { ko: "유행의", en: "current" },
  { ko: "과목", en: "curriculum" },
  { ko: "카레요리 카레로 맛을 내다", en: "curry" },
  { ko: "저주", en: "curse" },
  { ko: "커어튼", en: "curtain" },
  { ko: "곡선", en: "curve" },
  { ko: "보호", en: "custody" },
  { ko: "습관", en: "custom" },
  { ko: "고객", en: "customer" },
  { ko: "베다", en: "cut" },
  { ko: "귀여운", en: "cute" },
  { ko: "순환", en: "cycle" },
  { ko: "냉소적인", en: "cynical" },
  { ko: "아빠", en: "dad" },
  { ko: "낙농장", en: "dairy" },
  { ko: "댐", en: "dam" },
  { ko: "손해", en: "damage" },
  { ko: "축축한 습기 적시다", en: "damp" },
  { ko: "댄스", en: "dance" },
  { ko: "위험", en: "danger" },
  { ko: "au감히 -하다", en: "dare" },
  { ko: "어두운", en: "dark" },
  { ko: "귀여운", en: "darling" },
  { ko: "돌진", en: "dash" },
  { ko: "데이터베이스", en: "database" },
  { ko: "날짜", en: "date" },
  { ko: "딸", en: "daughter" },
  { ko: "새벽 날이 새다", en: "dawn" },
  { ko: "낮", en: "day" },
  { ko: "죽은", en: "dead" },
  { ko: "양", en: "deal" },
  { ko: "죽음", en: "death" },
  { ko: "토론 토론하다", en: "debate" },
  { ko: "빚", en: "debt" },
  { ko: "10년간", en: "decade" },
  { ko: "쇠퇴하다", en: "decay" },
  { ko: "점잖은", en: "decent" },
  { ko: "결정하다", en: "decide" },
  { ko: "결정", en: "decision" },
  { ko: "갑판", en: "deck" },
  { ko: "선언하다", en: "declare" },
  { ko: "기울다", en: "decline" },
  { ko: "장식하다", en: "decorate" },
  { ko: "감소하다", en: "decrease" },
  { ko: "봉납하다", en: "dedicate" },
  { ko: "깊은", en: "deep" },
  { ko: "패배", en: "defeat" },
  { ko: "방어", en: "defense" },
  { ko: "방어하다", en: "defend" },
  { ko: "피고 피고의", en: "defendant" },
  { ko: "결핍", en: "deficiency" },
  { ko: "결손", en: "deficit" },
  { ko: "정의하다", en: "define" },
  { ko: "일정한", en: "definite" },
  { ko: "지위를 낮추다", en: "degrade" },
  { ko: "도", en: "degree" },
  { ko: "늦추다", en: "delay" },
  { ko: "파견하다", en: "delegate" },
  { ko: "삭제하다", en: "delete" },
  { ko: "숙고하다", en: "deliberate" },
  { ko: "미묘한", en: "delicate" },
  { ko: "맛있는", en: "delicious" },
  { ko: "즐겁게하다 즐거워하다", en: "delight" },
  { ko: "인도하다", en: "deliver" },
  { ko: "요구하다", en: "demand" },
  { ko: "민주주의", en: "democracy" },
  { ko: "민주주의자", en: "democrat" },
  { ko: "악마", en: "demon" },
  { ko: "증명하다", en: "demonstrate" },
  { ko: "짙은", en: "dense" },
  { ko: "치과의사", en: "dentist" },
  { ko: "부정하다", en: "deny" },
  { ko: "부", en: "department" },
  { ko: "출발", en: "departure" },
  { ko: "좌우되다", en: "depend" },
  { ko: "종속", en: "dependence" },
  { ko: "묘사하다", en: "depict" },
  { ko: "예금", en: "deposit" },
  { ko: "억압하다", en: "depress" },
  { ko: "빼앗다", en: "deprive" },
  { ko: "이끌어 내다", en: "derive" },
  { ko: "내려오다", en: "descend" },
  { ko: "기술하다", en: "describe" },
  { ko: "서술", en: "description" },
  { ko: "버리다", en: "desert" },
  { ko: " -할 만하다", en: "deserve" },
  { ko: "디자인", en: "design" },
  { ko: "가리키다", en: "designate" },
  { ko: "바라다", en: "desire" },
  { ko: "책상", en: "desk" },
  { ko: "절망하다", en: "despair" },
  { ko: "절망적인", en: "desperate" },
  { ko: "-에도 불구하고 모욕", en: "despite" },
  { ko: "목적지", en: "destination" },
  { ko: "운명", en: "destiny" },
  { ko: "파괴하다", en: "destroy" },
  { ko: "파괴", en: "destruction" },
  { ko: "분리하다", en: "detach" },
  { ko: "상설", en: "detail" },
  { ko: "간파하다", en: "detect" },
  { ko: "결정하다", en: "determine" },
  { ko: "발달하다", en: "develop" },
  { ko: "고안", en: "device" },
  { ko: "악마", en: "devil" },
  { ko: "고안하다", en: "devise" },
  { ko: "바치다", en: "devote" },
  { ko: "당뇨병", en: "diabetes" },
  { ko: "대화", en: "dialogue" },
  { ko: "일기", en: "diary" },
  { ko: "받아쓰게 하다", en: "dictate" },
  { ko: "사전", en: "dictionary" },
  { ko: "죽다", en: "die" },
  { ko: "다른", en: "different" },
  { ko: "곤란한", en: "difficult" },
  { ko: "파다", en: "dig" },
  { ko: "위엄", en: "dignity" },
  { ko: "치수", en: "dimension" },
  { ko: "감소하다", en: "diminish" },
  { ko: "저녁식사를 하다", en: "dine" },
  { ko: "정찬", en: "dinner" },
  { ko: "담그다", en: "dip" },
  { ko: "외교관", en: "diplomat" },
  { ko: "지도하다", en: "direct" },
  { ko: "더러운", en: "dirty" },
  { ko: "불구가 된", en: "disabled" },
  { ko: "불리", en: "disadvantage" },
  { ko: "일치하지 않다", en: "disagree" },
  { ko: "안보이게 되다", en: "disappear" },
  { ko: "실망시키다", en: "disappoint" },
  { ko: "천재", en: "disaster" },
  { ko: "짐을부리다", en: "discharge" },
  { ko: "훈련", en: "discipline" },
  { ko: "나타내다", en: "disclose" },
  { ko: "할인", en: "discount" },
  { ko: "강연", en: "discourse" },
  { ko: "발견하다", en: "discover" },
  { ko: "분별하다", en: "discriminate" },
  { ko: "토론하다", en: "discuss" },
  { ko: "병", en: "disease" },
  { ko: "불쾌하게 하다", en: "disgust" },
  { ko: "접시", en: "dish" },
  { ko: "떠나게 하다", en: "dismiss" },
  { ko: "난잡", en: "disorder" },
  { ko: "바꾸어놓다", en: "displace" },
  { ko: "보이다", en: "display" },
  { ko: "배열하다", en: "dispose" },
  { ko: "논쟁하다", en: "dispute" },
  { ko: "분열시키다", en: "disrupt" },
  { ko: "떨어진", en: "distant" },
  { ko: "찌그러뜨리다", en: "distort" },
  { ko: "전환시키다", en: "distract" },
  { ko: "분배하다", en: "distribute" },
  { ko: "지구", en: "district" },
  { ko: "교란하다", en: "disturb" },
  { ko: "뛰어들다", en: "dive" },
  { ko: "다양한", en: "diverse" },
  { ko: "나누다", en: "divide" },
  { ko: "신의", en: "divine" },
  { ko: "이혼", en: "divorce" },
  { ko: "하다", en: "do" },
  { ko: "박사", en: "doctor" },
  { ko: "서류", en: "document" },
  { ko: "개", en: "dog" },
  { ko: "인형", en: "doll" },
  { ko: "돌고래", en: "dolphin" },
  { ko: "영토", en: "domain" },
  { ko: "가정의", en: "domestic" },
  { ko: "우세한", en: "dominant" },
  { ko: "증여하다", en: "donate" },
  { ko: "문", en: "door" },
  { ko: "1회복용량 투약하다", en: "dose" },
  { ko: "점", en: "dot" },
  { ko: "2배의", en: "double" },
  { ko: "의심", en: "doubt" },
  { ko: "아래로", en: "down" },
  { ko: "1다스", en: "dozen" },
  { ko: "초고", en: "draft" },
  { ko: "끌다", en: "drag" },
  { ko: "배수하다", en: "drain" },
  { ko: "당기다", en: "draw" },
  { ko: "제도사", en: "drawer" },
  { ko: "두려워하다 두려움", en: "dread" },
  { ko: "꿈", en: "dream" },
  { ko: "마시다", en: "drink" },
  { ko: "운전하다", en: "drive" },
  { ko: "방울", en: "drop" },
  { ko: "물에빠뜨리다", en: "drown" },
  { ko: "약제", en: "drug" },
  { ko: "마른", en: "dry" },
  { ko: "둘의", en: "dual" },
  { ko: "머리를 물 속에 쑥 쳐박다", en: "duck" },
  { ko: "지급기일이 된", en: "due" },
  { ko: "둔한", en: "dull" },
  { ko: "내버리다", en: "dump" },
  { ko: "-동안에", en: "during" },
  { ko: "먼지", en: "dust" },
  { ko: "의무", en: "duty" },
  { ko: "거주하다", en: "dwell" },
  { ko: "동적인", en: "dynamic" },
  { ko: "각각의", en: "each" },
  { ko: "열심인", en: "eager" },
  { ko: "귀", en: "ear" },
  { ko: "이른", en: "early" },
  { ko: "일하여 벌다", en: "earn" },
  { ko: "지구", en: "earth" },
  { ko: "안락", en: "ease" },
  { ko: "동쪽 동쪽의 동쪽으로", en: "east" },
  { ko: "쉬운", en: "easy" },
  { ko: "먹다", en: "eat" },
  { ko: "절약", en: "economy" },
  { ko: "끝머리", en: "edge" },
  { ko: "편집하다", en: "edit" },
  { ko: "교육하다", en: "educate" },
  { ko: "결과", en: "effect" },
  { ko: "효과적인", en: "effective" },
  { ko: "능률적인", en: "efficient" },
  { ko: "노력", en: "effort" },
  { ko: "알", en: "egg" },
  { ko: "어느 하나의", en: "either" },
  { ko: "공들인", en: "elaborate" },
  { ko: "선거하다", en: "elect" },
  { ko: "전기의", en: "electric" },
  { ko: "전자(학)의", en: "electronic" },
  { ko: "우아한", en: "elegant" },
  { ko: "요소", en: "element" },
  { ko: "기본의", en: "elementary" },
  { ko: "코끼리", en: "elephant" },
  { ko: "제거하다", en: "eliminate" },
  { ko: "그 밖에", en: "else" },
  { ko: "난처하게 하다", en: "embarrass" },
  { ko: "대사관", en: "embassy" },
  { ko: "포옹하다", en: "embrace" },
  { ko: "나오다", en: "emerge" },
  { ko: "비상사태", en: "emergency" },
  { ko: "방사하다", en: "emit" },
  { ko: "감정", en: "emotion" },
  { ko: "강조", en: "emphasis" },
  { ko: "제국", en: "empire" },
  { ko: "고용하다", en: "employ" },
  { ko: "빈", en: "empty" },
  { ko: "에워싸다", en: "enclose" },
  { ko: "조우", en: "encounter" },
  { ko: "용기를 돋우다", en: "encourage" },
  { ko: "끝", en: "end" },
  { ko: "견디다", en: "endure" },
  { ko: "적", en: "enemy" },
  { ko: "실시하다", en: "enforce" },
  { ko: "약속하다", en: "engage" },
  { ko: "엔진", en: "engine" },
  { ko: "기사", en: "engineer" },
  { ko: "향상하다", en: "enhance" },
  { ko: "즐기다", en: "enjoy" },
  { ko: "거대한", en: "enormous" },
  { ko: "충분한", en: "enough" },
  { ko: "명부에 올리다", en: "enroll" },
  { ko: "-을 책임지다", en: "ensure" },
  { ko: "들어가다", en: "enter" },
  { ko: "기획", en: "enterprise" },
  { ko: "즐겁게 하다", en: "entertain" },
  { ko: "열심인", en: "enthusiastic" },
  { ko: "전체의", en: "entire" },
  { ko: "자격을 주다", en: "entitle" },
  { ko: "들어감", en: "entry" },
  { ko: "봉투", en: "envelope" },
  { ko: "환경", en: "environment" },
  { ko: "질투", en: "envy" },
  { ko: "삽화", en: "episode" },
  { ko: "같은", en: "equal" },
  { ko: "같게하다", en: "equate" },
  { ko: "장비", en: "equipment" },
  { ko: "시대", en: "era" },
  { ko: "지우는 사람", en: "eraser" },
  { ko: "똑바로 선", en: "erect" },
  { ko: "잘못", en: "error" },
  { ko: "도망하다", en: "escape" },
  { ko: "호위하다", en: "escort" },
  { ko: "특히", en: "especially" },
  { ko: "본질적인", en: "essential" },
  { ko: "확립하다", en: "establish" },
  { ko: "토지", en: "estate" },
  { ko: "어림잡다", en: "estimate" },
  { ko: "등등", en: "etc" },
  { ko: "도덕상의", en: "ethical" },
  { ko: "인종의", en: "ethnic" },
  { ko: "비우다", en: "evacuate" },
  { ko: "평가하다", en: "evaluate" },
  { ko: '"저녁', en: "eve" },
  { ko: "-조차", en: "even" },
  { ko: "저녁", en: "evening" },
  { ko: "결국", en: "eventually" },
  { ko: "이전에", en: "ever" },
  { ko: "모든", en: "every" },
  { ko: "명백한", en: "evident" },
  { ko: "사악한", en: "evil" },
  { ko: "진화", en: "evolution" },
  { ko: "진화하다", en: "evolve" },
  { ko: "정확한", en: "exact" },
  { ko: "과장하다", en: "exaggerate" },
  { ko: "시험", en: "exam" },
  { ko: "시험하다", en: "examine" },
  { ko: "보기", en: "example" },
  { ko: "넘다", en: "exceed" },
  { ko: "우수한", en: "excellent" },
  { ko: "-을 제외하고는 제외하다", en: "except" },
  { ko: "초과", en: "excess" },
  { ko: "교환하다", en: "exchange" },
  { ko: "흥분시키다", en: "excite" },
  { ko: "배척하다", en: "exclude" },
  { ko: "배타적인", en: "exclusive" },
  { ko: "변명", en: "excuse" },
  { ko: "집행의", en: "executive" },
  { ko: "운동", en: "exercise" },
  { ko: "다 써버리다", en: "exhaust" },
  { ko: "보이다", en: "exhibit" },
  { ko: "존재하다", en: "exist" },
  { ko: "출구", en: "exit" },
  { ko: "외국의", en: "exotic" },
  { ko: "펴다", en: "expand" },
  { ko: "기대하다", en: "expect" },
  { ko: "지출", en: "expense" },
  { ko: "비용이 드는", en: "expensive" },
  { ko: "경험", en: "experience" },
  { ko: "실험", en: "experiment" },
  { ko: "숙련가", en: "expert" },
  { ko: "대가의 의견", en: "expertise" },
  { ko: "설명하다", en: "explain" },
  { ko: "명백한", en: "explicit" },
  { ko: "폭발시키다", en: "explode" },
  { ko: "탐험하다", en: "explore" },
  { ko: "수출하다 수출", en: "export" },
  { ko: '"쐬다', en: "expose" },
  { ko: "발표하다", en: "express" },
  { ko: "뻗다", en: "extend" },
  { ko: "넓이", en: "extent" },
  { ko: "외부의", en: "external" },
  { ko: "꺼진", en: "extinct" },
  { ko: "가외의", en: "extra" },
  { ko: "뽑아내다", en: "extract" },
  { ko: "이상한", en: "extraordinary" },
  { ko: "극단의", en: "extreme" },
  { ko: "눈", en: "eye" },
  { ko: "눈썹", en: "eyebrow" },
  { ko: "천", en: "fabric" },
  { ko: "얼굴", en: "face" },
  { ko: "쉽게하다", en: "facilitate" },
  { ko: "쉬움", en: "facility" },
  { ko: "사실", en: "fact" },
  { ko: "요소", en: "factor" },
  { ko: "공장", en: "factory" },
  { ko: "능력", en: "faculty" },
  { ko: "바래다", en: "fade" },
  { ko: "실패하다", en: "fail" },
  { ko: "기절하다", en: "faint" },
  { ko: "공평한", en: "fair" },
  { ko: "신용", en: "faith" },
  { ko: "떨어지다", en: "fall" },
  { ko: "거짓", en: "false" },
  { ko: "명성", en: "fame" },
  { ko: "친한", en: "familiar" },
  { ko: "가족", en: "family" },
  { ko: "유명한", en: "famous" },
  { ko: "(영화 등의)팬", en: "fan" },
  { ko: "공상", en: "fancy" },
  { ko: "환상적인", en: "fantastic" },
  { ko: "멀리", en: "far" },
  { ko: "요금", en: "fare" },
  { ko: "농장", en: "farm" },
  { ko: "황홀케 하다", en: "fascinate" },
  { ko: "빠른", en: "fast" },
  { ko: "단단히 고정시키다", en: "fasten" },
  { ko: "살찐", en: "fat" },
  { ko: "치명적인", en: "fatal" },
  { ko: "숙명", en: "fate" },
  { ko: "아버지", en: "father" },
  { ko: "결점", en: "fault" },
  { ko: "호의", en: "favor" },
  { ko: "마음에 드는 좋아하는 물건", en: "favorite" },
  { ko: "두려움", en: "fear" },
  { ko: "얼굴의 생김새", en: "feature" },
  { ko: "연방의", en: "federal" },
  { ko: "요금", en: "fee" },
  { ko: "음식(먹이)을 주다", en: "feed" },
  { ko: "만져보다", en: "feel" },
  { ko: "동무", en: "fellow" },
  { ko: "여성", en: "female" },
  { ko: "나루터", en: "ferry" },
  { ko: "비옥한", en: "fertile" },
  { ko: "열", en: "fever" },
  { ko: "소수의", en: "few" },
  { ko: "섬유", en: "fiber" },
  { ko: "들", en: "field" },
  { ko: "흉포한", en: "fierce" },
  { ko: "싸움", en: "fight" },
  { ko: "모습", en: "figure" },
  { ko: "종이끼우개", en: "file" },
  { ko: "가득 채우다", en: "fill" },
  { ko: "여과기 여과하다", en: "filter" },
  { ko: "최후의", en: "final" },
  { ko: "재정", en: "finance" },
  { ko: "발견하다", en: "find" },
  { ko: "훌륭한", en: "fine" },
  { ko: "손가락 손가락을 대다", en: "finger" },
  { ko: "끝내다", en: "finish" },
  { ko: "한정되어 있는", en: "finite" },
  { ko: "불", en: "fire" },
  { ko: "굳은", en: "firm" },
  { ko: "물고기", en: "fish" },
  { ko: "주먹", en: "fist" },
  { ko: "맞는", en: "fit" },
  { ko: "고정시키다", en: "fix" },
  { ko: "기", en: "flag" },
  { ko: "불꽃", en: "flame" },
  { ko: "번쩍임", en: "flash" },
  { ko: "편평한", en: "flat" },
  { ko: "(독특한)맛", en: "flavor" },
  { ko: "금", en: "flaw" },
  { ko: "달아나다", en: "flee" },
  { ko: "살", en: "flesh" },
  { ko: "구부리기 쉬운", en: "flexible" },
  { ko: "날기", en: "flight" },
  { ko: "튀기다 홱 움직이다 튀기기", en: "flip" },
  { ko: "뜨다", en: "float" },
  { ko: "무리", en: "flock" },
  { ko: "홍수", en: "flood" },
  { ko: "마룻바닥", en: "floor" },
  { ko: "번창하다", en: "flourish" },
  { ko: "흐르다", en: "flow" },
  { ko: "꽃", en: "flower" },
  { ko: "유동성의", en: "fluid" },
  { ko: "왈칵흐르다", en: "flush" },
  { ko: "날다", en: "fly" },
  { ko: "초점", en: "focus" },
  { ko: "안개", en: "fog" },
  { ko: "주름", en: "fold" },
  { ko: "사람들", en: "folk" },
  { ko: "쫓다", en: "follow" },
  { ko: "좋아하는", en: "fond" },
  { ko: "음식", en: "food" },
  { ko: "바보", en: "fool" },
  { ko: "발", en: "foot" },
  { ko: "축구", en: "football" },
  { ko: "대신에", en: "for" },
  { ko: "금하다", en: "forbid" },
  { ko: "힘", en: "force" },
  { ko: "예상", en: "forecast" },
  { ko: "이마", en: "forehead" },
  { ko: "외국의", en: "foreign" },
  { ko: "숲", en: "forest" },
  { ko: "영원히", en: "forever" },
  { ko: "잊다", en: "forget" },
  { ko: "용서하다", en: "forgive" },
  { ko: "모양", en: "form" },
  { ko: "형식상의", en: "formal" },
  { ko: "(서적의)체제", en: "format" },
  { ko: "형성", en: "formation" },
  { ko: "이전의", en: "former" },
  { ko: "공식", en: "formula" },
  { ko: "앞으로", en: "forth" },
  { ko: "운좋은", en: "fortunate" },
  { ko: "운", en: "fortune" },
  { ko: "공개토론회", en: "forum" },
  { ko: "앞쪽에", en: "forward" },
  { ko: "기르다", en: "foster" },
  { ko: "기초", en: "foundation" },
  { ko: "샘", en: "fountain" },
  { ko: "교활한 사람", en: "fox" },
  { ko: "분수", en: "fraction" },
  { ko: "구조", en: "frame" },
  { ko: "뼈대", en: "framework" },
  { ko: "솔직히", en: "frankly" },
  { ko: "자유로운", en: "free" },
  { ko: "얼다", en: "freeze" },
  { ko: "빈번한", en: "frequent" },
  { ko: "새로운", en: "fresh" },
  { ko: "친구", en: "friend" },
  { ko: "(갑자기 엄습하는)공포", en: "fright" },
  { ko: "개구리", en: "frog" },
  { ko: '"(분리', en: "from" },
  { ko: "정면", en: "front" },
  { ko: "서리", en: "frost" },
  { ko: "눈살을 찌푸리다", en: "frown" },
  { ko: "과일", en: "fruit" },
  { ko: "(계획 등을)좌절시키다", en: "frustrate" },
  { ko: "기름으로 튀기다", en: "fry" },
  { ko: "연료", en: "fuel" },
  { ko: "이행하다", en: "fulfil" },
  { ko: "가득찬", en: "full" },
  { ko: "즐거운 생각", en: "fun" },
  { ko: "기능", en: "function" },
  { ko: "기금", en: "fund" },
  { ko: "기초(기준)의", en: "fundamental" },
  { ko: "장사", en: "funeral" },
  { ko: "모피", en: "fur" },
  { ko: "노하여 펄펄뛰는", en: "furious" },
  { ko: "공급하다", en: "furnish" },
  { ko: "가구", en: "furniture" },
  { ko: "더우기", en: "furthermore" },
  { ko: "신관", en: "fuse" },
  { ko: "미래", en: "future" },
  { ko: "얻다", en: "gain" },
  { ko: "도박하다 도박 도박해서 잃다", en: "gamble" },
  { ko: "한 떼", en: "gang" },
  { ko: "갈라진 틈", en: "gap" },
  { ko: "차고", en: "garage" },
  { ko: "뜰", en: "garden" },
  { ko: "가솔린", en: "gasoline" },
  { ko: "문", en: "gate" },
  { ko: "그러모으다", en: "gather" },
  { ko: "지켜보다", en: "gaze" },
  { ko: "톱니바퀴", en: "gear" },
  { ko: "성", en: "gender" },
  { ko: "유전(인)자", en: "gene" },
  { ko: "일반적인", en: "general" },
  { ko: "낳다", en: "generate" },
  { ko: "일대", en: "generation" },
  { ko: "광대한", en: "generous" },
  { ko: "천재", en: "genius" },
  { ko: "유형", en: "genre" },
  { ko: "온화한", en: "gentle" },
  { ko: "신사", en: "gentleman" },
  { ko: "진짜의", en: "genuine" },
  { ko: "지리", en: "geography" },
  { ko: "지질학", en: "geology" },
  { ko: "몸짓", en: "gesture" },
  { ko: "얻다", en: "get" },
  { ko: "유령", en: "ghost" },
  { ko: "거인", en: "giant" },
  { ko: "선물", en: "gift" },
  { ko: "기린", en: "giraffe" },
  { ko: "소녀", en: "girl" },
  { ko: "주다", en: "give" },
  { ko: "기쁜", en: "glad" },
  { ko: "흘긋 봄", en: "glance" },
  { ko: "번쩍이는 빛", en: "glare" },
  { ko: "유리", en: "glass" },
  { ko: "흘끗 봄", en: "glimpse" },
  { ko: "공모양의", en: "global" },
  { ko: "영광", en: "glory" },
  { ko: "장갑", en: "glove" },
  { ko: "타다", en: "glow" },
  { ko: "아교", en: "glue" },
  { ko: "가다", en: "go" },
  { ko: "결승점", en: "goal" },
  { ko: "염소", en: "goat" },
  { ko: "신", en: "god" },
  { ko: "금", en: "gold" },
  { ko: "좋은", en: "good" },
  { ko: "안녕히 가세요", en: "goodbye" },
  { ko: "상품", en: "goods" },
  { ko: "호화로운", en: "gorgeous" },
  { ko: "다스리다", en: "govern" },
  { ko: "붙잡다(=snatch)", en: "grab" },
  { ko: "은총", en: "grace" },
  { ko: "등급", en: "grade" },
  { ko: "점차적인", en: "gradual" },
  { ko: "학위를 수여하다", en: "graduate" },
  { ko: "곡물", en: "grain" },
  { ko: "위대한", en: "grand" },
  { ko: "할아버지", en: "grandfather" },
  { ko: "받아들이다", en: "grant" },
  { ko: "포도", en: "grape" },
  { ko: "그려 놓은 듯한", en: "graphic" },
  { ko: "붙잡다", en: "grasp" },
  { ko: "풀밭", en: "grass" },
  { ko: "고맙게 생각하는", en: "grateful" },
  { ko: "무덤", en: "grave" },
  { ko: "커다란", en: "great" },
  { ko: "탐욕", en: "greed" },
  { ko: "초록색", en: "green" },
  { ko: "인사하다", en: "greet" },
  { ko: "회색의", en: "grey" },
  { ko: "심한 슬픔(deep sorrow)", en: "grief" },
  { ko: "잡기", en: "grip" },
  { ko: "식품잡화류", en: "grocery" },
  { ko: "총계의", en: "gross" },
  { ko: "땅", en: "ground" },
  { ko: "집단", en: "group" },
  { ko: "성장하다", en: "grow" },
  { ko: "보증하다", en: "guarantee" },
  { ko: "보호자", en: "guardian" },
  { ko: "추측(짐작)하다", en: "guess" },
  { ko: "손님", en: "guest" },
  { ko: "이끌다", en: "guide" },
  { ko: "지침", en: "guideline" },
  { ko: "죄지은", en: "guilty" },
  { ko: "만", en: "gulf" },
  { ko: "총", en: "gun" },
  { ko: "녀석", en: "guy" },
  { ko: "실내체조장", en: "gymnasium" },
  { ko: "습관", en: "habit" },
  { ko: "(동물의)자연번식지", en: "habitat" },
  { ko: "털", en: "hair" },
  { ko: "반", en: "half" },
  { ko: "회관", en: "hall" },
  { ko: "멈춰서다", en: "halt" },
  { ko: "망치", en: "hammer" },
  { ko: "손", en: "hand" },
  { ko: "불리한 조건", en: "handicap" },
  { ko: "손잡이", en: "handle" },
  { ko: "얼굴(자태)이 잘생긴", en: "handsome" },
  { ko: "걸다", en: "hang" },
  { ko: "(사건 등이)일어나다", en: "happen" },
  { ko: "행운의", en: "happy" },
  { ko: "항구", en: "harbor" },
  { ko: "단단한", en: "hard" },
  { ko: "거의 -아니다", en: "hardly" },
  { ko: "해", en: "harm" },
  { ko: "거친", en: "harsh" },
  { ko: "수확", en: "harvest" },
  { ko: "급함", en: "haste" },
  { ko: "(테있는)모자 모자를 씌우다", en: "hat" },
  { ko: "미워하다", en: "hate" },
  { ko: "자주가다", en: "haunt" },
  { ko: "가지(고 있)다", en: "have" },
  { ko: "위험", en: "hazard" },
  { ko: "(3인칭단수 남성)그", en: "he" },
  { ko: "머리", en: "head" },
  { ko: "두통", en: "headache" },
  { ko: "본부", en: "headquarters" },
  { ko: "고치다", en: "heal" },
  { ko: "건강", en: "health" },
  { ko: "듣다", en: "hear" },
  { ko: "심장", en: "heart" },
  { ko: "열", en: "heat" },
  { ko: "하늘", en: "heaven" },
  { ko: "무거운", en: "heavy" },
  { ko: "발뒤꿈치", en: "heel" },
  { ko: "높이", en: "height" },
  { ko: "상속인", en: "heir" },
  { ko: "헬리콥터", en: "helicopter" },
  { ko: "지옥", en: "hell" },
  { ko: "여보", en: "hello" },
  { ko: "돕다", en: "help" },
  { ko: "그러므로", en: "hence" },
  { ko: "여기에", en: "here" },
  { ko: "세습 재산", en: "heritage" },
  { ko: "영웅", en: "hero" },
  { ko: "주저하다", en: "hesitate" },
  { ko: "감추다", en: "hide" },
  { ko: "높은", en: "high" },
  { ko: "대도", en: "highway" },
  { ko: '"언덕', en: "hill" },
  { ko: "엉덩이", en: "hip" },
  { ko: "고용하다", en: "hire" },
  { ko: "역사", en: "history" },
  { ko: "명중하다", en: "hit" },
  { ko: "취미", en: "hobby" },
  { ko: "손에 갖고 있다", en: "hold" },
  { ko: "구멍", en: "hole" },
  { ko: "휴일", en: "holiday" },
  { ko: "신성한", en: "holy" },
  { ko: "가정", en: "home" },
  { ko: "숙제", en: "homework" },
  { ko: "정직한", en: "honest" },
  { ko: "벌꿀", en: "honey" },
  { ko: "명예", en: "honor" },
  { ko: "갈고리", en: "hook" },
  { ko: "희망", en: "hope" },
  { ko: "지평선", en: "horizon" },
  { ko: "뿔", en: "horn" },
  { ko: "공포", en: "horror" },
  { ko: "말", en: "horse" },
  { ko: "병원", en: "hospital" },
  { ko: '"주인', en: "host" },
  { ko: "볼모", en: "hostage" },
  { ko: "반대하는", en: "hostile" },
  { ko: "뜨거운", en: "hot" },
  { ko: "시간", en: "hour" },
  { ko: "집", en: "house" },
  { ko: "가족", en: "household" },
  { ko: "어떻게", en: "how" },
  { ko: "아무리", en: "however" },
  { ko: "꼭 껴안다", en: "hug" },
  { ko: "거대한", en: "huge" },
  { ko: "인간의", en: "human" },
  { ko: "유우머", en: "humor" },
  { ko: "100 100의", en: "hundred" },
  { ko: "배고픈", en: "hungry" },
  { ko: "사냥하다", en: "hunt" },
  { ko: "서두르다", en: "hurry" },
  { ko: "상처내다", en: "hurt" },
  { ko: "남편 절약하다", en: "husband" },
  { ko: "오두막", en: "hut" },
  { ko: "가설", en: "hypothesis" },
  { ko: '"나는', en: "I" },
  { ko: "얼음", en: "ice" },
  { ko: "관념", en: "idea" },
  { ko: "이상", en: "ideal" },
  { ko: "아주 동일한", en: "identical" },
  { ko: "동일시하다", en: "identify" },
  { ko: "공리", en: "ideology" },
  { ko: "만일 -이라면", en: "if" },
  { ko: "무시하다", en: "ignore" },
  { ko: "병든", en: "ill" },
  { ko: "환영", en: "illusion" },
  { ko: "설명하다", en: "illustrate" },
  { ko: "상상하다", en: "imagine" },
  { ko: "흉내내다", en: "imitate" },
  { ko: "직접의", en: "immediate" },
  { ko: "무한한", en: "immense" },
  { ko: "이주하다", en: "immigrate" },
  { ko: "면역성의", en: "immune" },
  { ko: "충격", en: "impact" },
  { ko: "제국의", en: "imperial" },
  { ko: "기구", en: "implement" },
  { ko: "함축하다", en: "imply" },
  { ko: "수입하다", en: "import" },
  { ko: "중요한", en: "important" },
  { ko: "부과하다", en: "impose" },
  { ko: "인상지우다", en: "impress" },
  { ko: "개선하다", en: "improve" },
  { ko: "-속에", en: "in" },
  { ko: "자극적인", en: "incentive" },
  { ko: "사건", en: "incident" },
  { ko: "기울이다", en: "incline" },
  { ko: "포함하다", en: "include" },
  { ko: "수입", en: "income" },
  { ko: "합동시키다", en: "incorporate" },
  { ko: "늘다", en: "increase" },
  { ko: "믿을 수 없는", en: "incredible" },
  { ko: "참으로", en: "indeed" },
  { ko: "독립한", en: "independent" },
  { ko: "색인", en: "index" },
  { ko: "지적하다", en: "indicate" },
  { ko: "개인", en: "individual" },
  { ko: "꾀다", en: "induce" },
  { ko: "공업", en: "industry" },
  { ko: "피할 수 없는", en: "inevitable" },
  { ko: "유아", en: "infant" },
  { ko: "감염시키다", en: "infect" },
  { ko: "추론하다", en: "infer" },
  { ko: "부풀게 하다", en: "inflate" },
  { ko: "영향력", en: "influence" },
  { ko: "알리다", en: "inform" },
  { ko: "비공식의", en: "informal" },
  { ko: "성분", en: "ingredient" },
  { ko: "살다", en: "inhabit" },
  { ko: "생태의", en: "inherent" },
  { ko: "금하다", en: "inhibit" },
  { ko: "처음의", en: "initial" },
  { ko: "시작하다", en: "initiate" },
  { ko: "주사하다", en: "inject" },
  { ko: "해치다", en: "injure" },
  { ko: "여인숙", en: "inn" },
  { ko: "무구한", en: "innocent" },
  { ko: "새롭게 하다", en: "innovate" },
  { ko: "투입", en: "input" },
  { ko: "묻다", en: "inquire" },
  { ko: "곤충", en: "insect" },
  { ko: "끼워넣다", en: "insert" },
  { ko: "안쪽", en: "inside" },
  { ko: "통찰(력)", en: "insight" },
  { ko: "주장하다", en: "insist" },
  { ko: "검사하다", en: "inspect" },
  { ko: "영감을 주다", en: "inspire" },
  { ko: "설치하다", en: "install" },
  { ko: "실례", en: "instance" },
  { ko: "즉시의", en: "instant" },
  { ko: "그 대신에", en: "instead" },
  { ko: "본능", en: "instinct" },
  { ko: "만들다", en: "institute" },
  { ko: "가르치다", en: "instruct" },
  { ko: "기구", en: "instrument" },
  { ko: "모욕하다", en: "insult" },
  { ko: "보증하다", en: "insure" },
  { ko: "통합하다", en: "integrate" },
  { ko: "지적인", en: "intellectual" },
  { ko: "지적인", en: "intelligent" },
  { ko: "-할 작정이다", en: "intend" },
  { ko: "강렬한", en: "intense" },
  { ko: "의향", en: "intent" },
  { ko: "서로 작용하다", en: "interact" },
  { ko: "흥미", en: "interest" },
  { ko: "간섭하다", en: "interfere" },
  { ko: "중간의 중간물", en: "intermediate" },
  { ko: "내부의", en: "internal" },
  { ko: "국제적인", en: "international" },
  { ko: "해석하다", en: "interpret" },
  { ko: "훼방놓다", en: "interrupt" },
  { ko: "간격", en: "interval" },
  { ko: "사이에 들다", en: "intervene" },
  { ko: "친밀한", en: "intimate" },
  { ko: "-안으로", en: "into" },
  { ko: "음모", en: "intrigue" },
  { ko: "안으로 들이다", en: "introduce" },
  { ko: "침입하다", en: "invade" },
  { ko: "발명하다", en: "invent" },
  { ko: "투자하다", en: "invest" },
  { ko: "조사하다", en: "investigate" },
  { ko: "초대하다", en: "invite" },
  { ko: "말아넣다", en: "involve" },
  { ko: "쇠", en: "iron" },
  { ko: "반어", en: "irony" },
  { ko: "노하게 하다", en: "irritate" },
  { ko: "섬", en: "island" },
  { ko: "고립시키다", en: "isolate" },
  { ko: "그것은", en: "it" },
  { ko: "조항", en: "item" },
  { ko: "교도소", en: "jail" },
  { ko: "(아가리가 넓은)항아리", en: "jar" },
  { ko: "턱", en: "jaw" },
  { ko: "청바지", en: "jeans" },
  { ko: "(가스등의)분출", en: "jet" },
  { ko: "일", en: "job" },
  { ko: "살짝 밀다 덜커덕 움직이다 고르지 않음", en: "jog" },
  { ko: "결합하다", en: "join" },
  { ko: "이음매", en: "joint" },
  { ko: "농담", en: "joke" },
  { ko: "일간신문", en: "journal" },
  { ko: "여행", en: "journey" },
  { ko: "즐거움", en: "joy" },
  { ko: "재판관", en: "judge" },
  { ko: "사법의", en: "judicial" },
  { ko: "손아래사람", en: "junior" },
  { ko: "배심", en: "jury" },
  { ko: "올바른", en: "just" },
  { ko: "정의", en: "justice" },
  { ko: "옳다고 하다", en: "justify" },
  { ko: "날카로운", en: "keen" },
  { ko: "계속하다", en: "keep" },
  { ko: "열쇠", en: "key" },
  { ko: "걷어차다", en: "kick" },
  { ko: "아이", en: "kid" },
  { ko: "죽이다", en: "kill" },
  { ko: "친절한", en: "kind" },
  { ko: "왕", en: "king" },
  { ko: "연장통", en: "kit" },
  { ko: "부엌", en: "kitchen" },
  { ko: "무릎", en: "knee" },
  { ko: "나이프", en: "knife" },
  { ko: "(중세의)기사", en: "knight" },
  { ko: "치다", en: "knock" },
  { ko: "매듭(=tie)", en: "knot" },
  { ko: "알다", en: "know" },
  { ko: "라벨", en: "label" },
  { ko: "노동", en: "labor" },
  { ko: "실험실", en: "laboratory" },
  { ko: "결핍", en: "lack" },
  { ko: "사닥다리", en: "ladder" },
  { ko: "귀부인", en: "lady" },
  { ko: "호수", en: "lake" },
  { ko: "어린 양", en: "lamb" },
  { ko: "등", en: "lamp" },
  { ko: "뭍", en: "land" },
  { ko: "풍경", en: "landscape" },
  { ko: "좁은길", en: "lane" },
  { ko: "언어", en: "language" },
  { ko: "무릎", en: "lap" },
  { ko: "큰", en: "large" },
  { ko: "계속하다", en: "last" },
  { ko: "늦은", en: "late" },
  { ko: "뒤쪽의", en: "latter" },
  { ko: "(소리내어)웃다", en: "laugh" },
  { ko: "진수시키다", en: "launch" },
  { ko: "세탁물", en: "laundry" },
  { ko: "법률", en: "law" },
  { ko: "잔디밭", en: "lawn" },
  { ko: "법률가", en: "lawyer" },
  { ko: "눕히다", en: "lay" },
  { ko: "층", en: "layer" },
  { ko: "게으른", en: "lazy" },
  { ko: "이끌다", en: "lead" },
  { ko: "잎", en: "leaf" },
  { ko: "샘", en: "leak" },
  { ko: "기대다", en: "lean" },
  { ko: "껑충 뛰다", en: "leap" },
  { ko: "배우다", en: "learn" },
  { ko: "임대차", en: "lease" },
  { ko: "무두질한 가죽", en: "leather" },
  { ko: "남기고가다", en: "leave" },
  { ko: "강의", en: "lecture" },
  { ko: "왼쪽의", en: "left" },
  { ko: "다리", en: "leg" },
  { ko: "법률상의", en: "legal" },
  { ko: "전설", en: "legend" },
  { ko: "법률을 제정하다", en: "legislate" },
  { ko: "합법의", en: "legitimate" },
  { ko: "틈", en: "leisure" },
  { ko: "빌리다", en: "lend" },
  { ko: "학과", en: "lesson" },
  { ko: "시키다", en: "let" },
  { ko: "편지", en: "letter" },
  { ko: "수평의", en: "level" },
  { ko: "자유주의의", en: "liberal" },
  { ko: "자유", en: "liberty" },
  { ko: "도서관", en: "library" },
  { ko: "면허", en: "license" },
  { ko: "뚜껑", en: "lid" },
  { ko: "눕다", en: "lie" },
  { ko: "끌어올리다", en: "lift" },
  { ko: "빛", en: "light" },
  { ko: "좋아하다", en: "like" },
  { ko: "있을 법한", en: "likely" },
  { ko: '"같이', en: "likewise" },
  { ko: "한계", en: "limit" },
  { ko: "선", en: "line" },
  { ko: "말의", en: "linguistic" },
  { ko: "사슬의 고리", en: "link" },
  { ko: "사자", en: "lion" },
  { ko: "입술", en: "lip" },
  { ko: "액체", en: "liquid" },
  { ko: "일람표", en: "list" },
  { ko: "경청하다", en: "listen" },
  { ko: "문자의", en: "literal" },
  { ko: "문학", en: "literature" },
  { ko: "작은", en: "little" },
  { ko: "살다", en: "live" },
  { ko: "거실", en: "livingroom" },
  { ko: "짐", en: "load" },
  { ko: "대부", en: "loan" },
  { ko: "장소의", en: "local" },
  { ko: "관청 등을 두다", en: "locate" },
  { ko: "자물쇠", en: "lock" },
  { ko: "통나무", en: "log" },
  { ko: "논리학", en: "logic" },
  { ko: "혼자의", en: "lone" },
  { ko: '"(길이', en: "long" },
  { ko: "보다", en: "look" },
  { ko: "풀어진", en: "loose" },
  { ko: "잃다", en: "lose" },
  { ko: "잃음", en: "loss" },
  { ko: "제비", en: "lot" },
  { ko: "시끄러운", en: "loud" },
  { ko: "빈둥거리다", en: "lounge" },
  { ko: "사랑", en: "love" },
  { ko: "낮은", en: "low" },
  { ko: "충성스러운", en: "loyal" },
  { ko: "운", en: "luck" },
  { ko: "덩어리", en: "lump" },
  { ko: "점심", en: "lunch" },
  { ko: "사치", en: "luxury" },
  { ko: "기계", en: "machine" },
  { ko: "미친", en: "mad" },
  { ko: "잡지", en: "magazine" },
  { ko: "자석", en: "magnet" },
  { ko: "장대한", en: "magnificent" },
  { ko: "우편물", en: "mail" },
  { ko: "주요한", en: "main" },
  { ko: "계속하다", en: "maintain" },
  { ko: "큰쪽의", en: "major" },
  { ko: "대다수", en: "majority" },
  { ko: "만들다", en: "make" },
  { ko: "남성의", en: "male" },
  { ko: "남자", en: "man" },
  { ko: "관리하다", en: "manage" },
  { ko: "명백히 하다", en: "manifest" },
  { ko: "(손으로)다루다", en: "manipulate" },
  { ko: "방법", en: "manner" },
  { ko: "제조하다", en: "manufacture" },
  { ko: "많은", en: "many" },
  { ko: "지도", en: "map" },
  { ko: "가장자리", en: "margin" },
  { ko: "바다의", en: "marine" },
  { ko: "표", en: "mark" },
  { ko: "결혼하다", en: "marry" },
  { ko: "경이", en: "marvel" },
  { ko: "덩어리", en: "mass" },
  { ko: "장", en: "master" },
  { ko: "성냥", en: "match" },
  { ko: "상대", en: "mate" },
  { ko: "원료", en: "material" },
  { ko: "수학", en: "mathematics" },
  { ko: "물질", en: "matter" },
  { ko: "익은", en: "mature" },
  { ko: "최고점", en: "maximum" },
  { ko: '"5월  청춘', en: "may" },
  { ko: "아마", en: "maybe" },
  { ko: "시장", en: "mayor" },
  { ko: "식사", en: "meal" },
  { ko: "의미하다", en: "mean" },
  { ko: "그동안 그 사이에", en: "meantime" },
  { ko: "그동안", en: "meanwhile" },
  { ko: "재다", en: "measure" },
  { ko: "(식용짐승의)고기", en: "meat" },
  { ko: "직공", en: "mechanic" },
  { ko: "(기계)장치", en: "mechanism" },
  { ko: "중재하다", en: "mediate" },
  { ko: "의학의", en: "medical" },
  { ko: "약", en: "medicine" },
  { ko: "중세(풍)의", en: "medieval" },
  { ko: "중간", en: "medium" },
  { ko: "-을 만나다", en: "meet" },
  { ko: "녹다", en: "melt" },
  { ko: "기억", en: "memory" },
  { ko: "마음의", en: "mental" },
  { ko: "말하다", en: "mention" },
  { ko: "상인", en: "merchant" },
  { ko: "단순한", en: "mere" },
  { ko: "합병하다", en: "merge" },
  { ko: "장점", en: "merit" },
  { ko: "혼란", en: "mess" },
  { ko: "금속", en: "metal" },
  { ko: "방법", en: "method" },
  { ko: "수도권(의)", en: "metropolitan" },
  { ko: "확성기", en: "microphone" },
  { ko: "극초단파 전자레인지로 요리하다", en: "microwave" },
  { ko: "한복판의", en: "middle" },
  { ko: "힘", en: "might" },
  { ko: "이주하다", en: "migrate" },
  { ko: "온후한", en: "mild" },
  { ko: "군의", en: "military" },
  { ko: "젖", en: "milk" },
  { ko: "멧돌", en: "mill" },
  { ko: "백만", en: "million" },
  { ko: "마음", en: "mind" },
  { ko: "광산업자", en: "miner" },
  { ko: "광물", en: "mineral" },
  { ko: "최소(한도)의", en: "minimal" },
  { ko: "최소 한도", en: "minimum" },
  { ko: "장관(목사)의 직(소임)", en: "ministry" },
  { ko: "작은 편의", en: "minor" },
  { ko: "분", en: "minute" },
  { ko: "기적", en: "miracle" },
  { ko: "거울", en: "mirror" },
  { ko: "미혼 여성 실수하다", en: "miss" },
  { ko: "미사일", en: "missile" },
  { ko: "사명", en: "mission" },
  { ko: "틀리다", en: "mistake" },
  { ko: "섞다", en: "mix" },
  { ko: "움직이기 쉬운", en: "mobile" },
  { ko: "조롱하다", en: "mock" },
  { ko: "방법", en: "mode" },
  { ko: "절제하는", en: "moderate" },
  { ko: "현대의", en: "modern" },
  { ko: "겸손한", en: "modest" },
  { ko: "변경하다", en: "modify" },
  { ko: "습기", en: "moisture" },
  { ko: "분자", en: "molecule" },
  { ko: "순간", en: "moment" },
  { ko: "금전", en: "money" },
  { ko: "충고자", en: "monitor" },
  { ko: "원숭이", en: "monkey" },
  { ko: "괴물", en: "monster" },
  { ko: "월", en: "month" },
  { ko: "기념비", en: "monument" },
  { ko: "(일시적인)기분", en: "mood" },
  { ko: "달", en: "moon" },
  { ko: "도덕의", en: "moral" },
  { ko: "그 위에", en: "moreover" },
  { ko: "아침", en: "morning" },
  { ko: "죽을운명의", en: "mortal" },
  { ko: "어머니", en: "mother" },
  { ko: "운동", en: "motion" },
  { ko: "동기", en: "motive" },
  { ko: "산", en: "mount" },
  { ko: "산", en: "mountain" },
  { ko: "새앙쥐", en: "mouse" },
  { ko: "입", en: "mouth" },
  { ko: "움직이다", en: "move" },
  { ko: "영화", en: "movie" },
  { ko: "많은", en: "much" },
  { ko: "진흙", en: "mud" },
  { ko: "복합의", en: "multiple" },
  { ko: "늘리다", en: "multiply" },
  { ko: "살인", en: "murder" },
  { ko: "근육", en: "muscle" },
  { ko: "박물관", en: "museum" },
  { ko: "버섯", en: "mushroom" },
  { ko: "음악", en: "music" },
  { ko: "-해야 한다", en: "must" },
  { ko: "상호의", en: "mutual" },
  { ko: "신화", en: "myth" },
  { ko: "손톱", en: "nail" },
  { ko: "소박한", en: "naive" },
  { ko: "발가벗은", en: "naked" },
  { ko: "이름", en: "name" },
  { ko: "유모", en: "nanny" },
  { ko: "이야기하다", en: "narrate" },
  { ko: "좁은", en: "narrow" },
  { ko: "불쾌한", en: "nasty" },
  { ko: "국가", en: "nation" },
  { ko: "타고난", en: "native" },
  { ko: "자연", en: "nature" },
  { ko: "해군(력)", en: "navy" },
  { ko: "가까이 -의 가까이에 가까운 접근하다", en: "near" },
  { ko: "산뜻한", en: "neat" },
  { ko: "필요한", en: "necessary" },
  { ko: "목", en: "neck" },
  { ko: "필요", en: "need" },
  { ko: "바늘 바늘로 꿰매다 바느질하다 아슬아슬한", en: "needle" },
  { ko: "부정적인", en: "negative" },
  { ko: "게을리 하다", en: "neglect" },
  { ko: "교섭하다", en: "negotiate" },
  { ko: "이웃사람(나라)", en: "neighbor" },
  { ko: "(둘중)어느쪽도 -아니다 -도 아니다", en: "neither" },
  { ko: "조카", en: "nephew" },
  { ko: "신경의", en: "nervous" },
  { ko: "보금자리", en: "nest" },
  { ko: "그물", en: "net" },
  { ko: "그물세공", en: "network" },
  { ko: "중립의", en: "neutral" },
  { ko: "결코 -아니다", en: "never" },
  { ko: "그럼에도 불구하고", en: "nevertheless" },
  { ko: "새로운", en: "new" },
  { ko: "신문", en: "newspaper" },
  { ko: "다음의", en: "next" },
  { ko: "니스(프랑스 남부의 항구도시)", en: "nice" },
  { ko: "밤", en: "night" },
  { ko: "악몽", en: "nightmare" },
  { ko: "무의", en: "no" },
  { ko: "고귀한", en: "noble" },
  { ko: "아무도 -않다 하찮은 사람", en: "nobody" },
  { ko: "끄덕이다", en: "nod" },
  { ko: "소리", en: "noise" },
  { ko: "추천하다", en: "nominate" },
  { ko: "아무도(조금도)-않다 조금도(결코)-않다", en: "none" },
  { ko: "역시", en: "nonetheless" },
  { ko: "허튼 소리", en: "nonsense" },
  { ko: "정오", en: "noon" },
  { ko: "-도 또한-않다", en: "nor" },
  { ko: "표준", en: "norm" },
  { ko: "표준(의)", en: "normal" },
  { ko: '"북', en: "north" },
  { ko: "코", en: "nose" },
  { ko: "아니다", en: "not" },
  { ko: "기록", en: "note" },
  { ko: "아무것도 …없다", en: "nothing" },
  { ko: '"통지', en: "notice" },
  { ko: '"n', en: "notion" },
  { ko: "소설", en: "novel" },
  { ko: "지금", en: "now" },
  { ko: '"오늘날에는', en: "nowadays" },
  { ko: "아무데도 …없다", en: "nowhere" },
  { ko: '"핵의', en: "nuclear" },
  { ko: "수", en: "number" },
  { ko: '"다 수의', en: "numerous" },
  { ko: "수녀 집비둘기의 일종", en: "nun" },
  { ko: "유모", en: "nurse" },
  { ko: "견과", en: "nut" },
  { ko: "참나무", en: "oak" },
  { ko: "따르다", en: "obey" },
  { ko: "사물", en: "object" },
  { ko: "객관적인", en: "objective" },
  { ko: "(의무를)별수없이 -하게하다", en: "oblige" },
  { ko: "관찰하다", en: "observe" },
  { ko: "늘러붙다", en: "obsess" },
  { ko: "얻다", en: "obtain" },
  { ko: "명백한", en: "obvious" },
  { ko: "경우", en: "occasion" },
  { ko: "일직업", en: "occupation" },
  { ko: "차지하다", en: "occupy" },
  { ko: "일어나다", en: "occur" },
  { ko: "대양", en: "ocean" },
  { ko: "묘한", en: "odd" },
  { ko: "출신의", en: "of" },
  { ko: "떨어져", en: "off" },
  { ko: "성나게 하다", en: "offend" },
  { ko: "권하다", en: "offer" },
  { ko: "임무", en: "office" },
  { ko: "공무원", en: "officer" },
  { ko: "공무원", en: "official" },
  { ko: "자주", en: "often" },
  { ko: "기름", en: "oil" },
  { ko: "늙은", en: "old" },
  { ko: "올리브나무", en: "olive" },
  { ko: "위에", en: "on" },
  { ko: "한번", en: "once" },
  { ko: "하나(의)", en: "one" },
  { ko: "유일한", en: "only" },
  { ko: "열다", en: "open" },
  { ko: "움직이다", en: "operate" },
  { ko: "의견", en: "opinion" },
  { ko: "기회", en: "opportunity" },
  { ko: "반대하다", en: "oppose" },
  { ko: "낙천가", en: "optimist" },
  { ko: "선택(권의 자유)", en: "option" },
  { ko: "혹은", en: "or" },
  { ko: "구두의", en: "oral" },
  { ko: "궤도", en: "orbit" },
  { ko: "관현악단", en: "orchestra" },
  { ko: "순서", en: "order" },
  { ko: "보통의", en: "ordinary" },
  { ko: "(생물의)기관", en: "organ" },
  { ko: "유기체의", en: "organic" },
  { ko: "조직하다", en: "organize" },
  { ko: "동양 동양의 동쪽으로 향하게 하다", en: "orient" },
  { ko: "기원", en: "origin" },
  { ko: "다른 다른 것 그렇지 않고", en: "other" },
  { ko: "딴 방법으로는", en: "otherwise" },
  { ko: "au해야만 하다", en: "ought" },
  { ko: "삵괭이", en: "ounce" },
  { ko: "밖으로", en: "out" },
  { ko: "결과", en: "outcome" },
  { ko: "윤곽", en: "outline" },
  { ko: "산출", en: "output" },
  { ko: "불법(적인 행위)", en: "outrage" },
  { ko: "눈에 띄는", en: "outstanding" },
  { ko: "위쪽", en: "over" },
  { ko: "포괄(전면)적인 덧옷", en: "overall" },
  { ko: "이기다", en: "overcome" },
  { ko: "머리위에 머리 위의", en: "overhead" },
  { ko: "겹치다", en: "overlap" },
  { ko: "내려다 보다", en: "overlook" },
  { ko: "전날밤의", en: "overnight" },
  { ko: "해외(로부터)의", en: "oversea" },
  { ko: "압도하다", en: "overwhelm" },
  { ko: "지불할 의무가 있다", en: "owe" },
  { ko: "자기자신의 소유하다", en: "own" },
  { ko: "한걸음", en: "pace" },
  { ko: "꾸러미", en: "pack" },
  { ko: "다발", en: "packet" },
  { ko: "(및에)덧대는 것", en: "pad" },
  { ko: "고통", en: "pain" },
  { ko: "도료", en: "paint" },
  { ko: "한쌍", en: "pair" },
  { ko: "궁전", en: "palace" },
  { ko: "창백한", en: "pale" },
  { ko: "손바닥", en: "palm" },
  { ko: "남비 사금 등을 남비로 가려내다", en: "pan" },
  { ko: "판벽널", en: "panel" },
  { ko: "돌연한공포", en: "panic" },
  { ko: "바지", en: "pants" },
  { ko: "종이", en: "paper" },
  { ko: "(문장의)절", en: "paragraph" },
  { ko: "평행의", en: "parallel" },
  { ko: "용서하다 용서", en: "pardon" },
  { ko: "어버이", en: "parent" },
  { ko: "공원", en: "park" },
  { ko: "의회", en: "parliament" },
  { ko: "부분", en: "part" },
  { ko: "참가하다", en: "participate" },
  { ko: "입자", en: "particle" },
  { ko: "특수한", en: "particular" },
  { ko: "지나가다", en: "pass" },
  { ko: '"통행', en: "passage" },
  { ko: "승객", en: "passenger" },
  { ko: "정열", en: "passion" },
  { ko: "여권", en: "passport" },
  { ko: "과거", en: "past" },
  { ko: "톡톡 가볍게 치다", en: "pat" },
  { ko: "깁는 헝겊", en: "patch" },
  { ko: "전매특허권 전매특허의", en: "patent" },
  { ko: "작은 길", en: "path" },
  { ko: "인내심이 강한 환자", en: "patient" },
  { ko: "순회", en: "patrol" },
  { ko: "모범", en: "pattern" },
  { ko: "중지", en: "pause" },
  { ko: "(도로를)포장하다", en: "pave" },
  { ko: "지불하다", en: "pay" },
  { ko: "평화", en: "peace" },
  { ko: "(뾰족한)끝", en: "peak" },
  { ko: "서양배", en: "pear" },
  { ko: "농부", en: "peasant" },
  { ko: "껍질을 벗기다 벗어지다 껍질", en: "peel" },
  { ko: "동료", en: "peer" },
  { ko: "벌", en: "penalty" },
  { ko: "연필 연필로 쓰다", en: "pencil" },
  { ko: "사람들", en: "people" },
  { ko: "고추", en: "pepper" },
  { ko: "-에 의하여", en: "per" },
  { ko: "지각하다", en: "perceive" },
  { ko: "완전한", en: "perfect" },
  { ko: "다하다", en: "perform" },
  { ko: "아마", en: "perhaps" },
  { ko: "시간", en: "period" },
  { ko: "영구의", en: "permanent" },
  { ko: "허가하다", en: "permit" },
  { ko: "고집하다", en: "persist" },
  { ko: "사람", en: "person" },
  { ko: "개성", en: "personality" },
  { ko: "원근법의 원근 화법", en: "perspective" },
  { ko: "설득하다", en: "persuade" },
  { ko: "애완동물", en: "pet" },
  { ko: "국면", en: "phase" },
  { ko: "현상", en: "phenomenon" },
  { ko: "철학", en: "philosophy" },
  { ko: "사진 촬영하다", en: "photograph" },
  { ko: "구", en: "phrase" },
  { ko: "물질의", en: "physical" },
  { ko: "물리학", en: "physics" },
  { ko: "따다", en: "pick" },
  { ko: "소풍", en: "picnic" },
  { ko: "그림", en: "picture" },
  { ko: "한 조각", en: "piece" },
  { ko: "돼지", en: "pig" },
  { ko: "쌓아 올린 것", en: "pile" },
  { ko: "알약", en: "pill" },
  { ko: "핀 핀으로 꽂다", en: "pin" },
  { ko: "꼬집다", en: "pinch" },
  { ko: "소나무 수척해 지다", en: "pine" },
  { ko: "연분홍색", en: "pink" },
  { ko: "개척자", en: "pioneer" },
  { ko: "던지다", en: "pitch" },
  { ko: "불쌍히 여김", en: "pity" },
  { ko: "장소", en: "place" },
  { ko: "분명한", en: "plain" },
  { ko: "계획", en: "plan" },
  { ko: "행성", en: "planet" },
  { ko: "실물", en: "plant" },
  { ko: "판", en: "plate" },
  { ko: "단", en: "platform" },
  { ko: "놀다", en: "play" },
  { ko: "기분 좋은", en: "pleasant" },
  { ko: "기쁘게 하다", en: "please" },
  { ko: "즐거움", en: "pleasure" },
  { ko: "많음", en: "plenty" },
  { ko: "음모", en: "plot" },
  { ko: "더하기의 -외에", en: "plus" },
  { ko: "오후", en: "P.M." },
  { ko: "포켓", en: "pocket" },
  { ko: "시", en: "poem" },
  { ko: "시인", en: "poet" },
  { ko: "점", en: "point" },
  { ko: "독", en: "poison" },
  { ko: "남극의", en: "polar" },
  { ko: "폴란드사람", en: "pole" },
  { ko: "경찰 경비하다", en: "police" },
  { ko: "정책", en: "policy" },
  { ko: '"닦다', en: "polish" },
  { ko: "공손한", en: "polite" },
  { ko: "정치", en: "politics" },
  { ko: "투표", en: "poll" },
  { ko: "-을 더럽히다", en: "pollute" },
  { ko: '"못', en: "pond" },
  { ko: "판돈", en: "pool" },
  { ko: '"가난한 부족한', en: "poor" },
  { ko: "팝", en: "pop" },
  { ko: "로마 교황  최고 권위자로 자처하는 사람", en: "pope" },
  { ko: '"민중 의', en: "popular" },
  { ko: "인구", en: "population" },
  { ko: "돼지고기", en: "pork" },
  { ko: '"항구', en: "port" },
  { ko: '"일부', en: "portion" },
  { ko: "초상", en: "portrait" },
  { ko: '"자세', en: "pose" },
  { ko: "위치", en: "position" },
  { ko: '"명확한', en: "positive" },
  { ko: "소유하다", en: "possess" },
  { ko: "가능한", en: "possible" },
  { ko: "기둥", en: "post" },
  { ko: "포스터", en: "poster" },
  { ko: "단지", en: "pot" },
  { ko: "감자", en: "potato" },
  { ko: "가능한", en: "potential" },
  { ko: "따르다", en: "pour" },
  { ko: "가루", en: "powder" },
  { ko: "힘", en: "power" },
  { ko: "실제의", en: "practical" },
  { ko: "연습", en: "practice" },
  { ko: "칭찬", en: "praise" },
  { ko: "빌다", en: "pray" },
  { ko: "설교하다", en: "preach" },
  { ko: "-에 앞서다", en: "precede" },
  { ko: "비싼", en: "precious" },
  { ko: "정확한", en: "precise" },
  { ko: "약탈자", en: "predator" },
  { ko: '"예언하다', en: "predict" },
  { ko: '"오히려 …을 좋아하다', en: "prefer" },
  { ko: "임신한 충만한", en: "pregnant" },
  { ko: '"편견', en: "prejudice" },
  { ko: '"국무 총리', en: "premier" },
  { ko: '"할증금', en: "premium" },
  { ko: '"준비하 다', en: "prepare" },
  { ko: '"명령하다', en: "prescribe" },
  { ko: '"존재', en: "presence" },
  { ko: '"있는', en: "present" },
  { ko: '"보호하다', en: "preserve" },
  { ko: "대통령 회장", en: "president" },
  { ko: "강제로 모집하다", en: "press" },
  { ko: "가정하다", en: "presume" },
  { ko: "핑계삼다", en: "pretend" },
  { ko: '"예쁜', en: "pretty" },
  { ko: '"이기다', en: "prevail" },
  { ko: '"막다', en: "prevent" },
  { ko: '"앞의', en: "previous" },
  { ko: "먹이", en: "prey" },
  { ko: '"값', en: "price" },
  { ko: "자존심", en: "pride" },
  { ko: "성직자", en: "priest" },
  { ko: '"첫째의', en: "primary" },
  { ko: '"수위의', en: "prime" },
  { ko: '"원시의', en: "primitive" },
  { ko: '"왕자', en: "prince" },
  { ko: '"주요한', en: "principal" },
  { ko: '"원리', en: "principle" },
  { ko: '"인쇄하다', en: "print" },
  { ko: '"이전의', en: "prior" },
  { ko: "교도소", en: "prison" },
  { ko: '"남의 눈을 피함', en: "privacy" },
  { ko: '"사적인', en: "private" },
  { ko: '"특권', en: "privilege" },
  { ko: '"상', en: "prize" },
  { ko: '"아마', en: "probably" },
  { ko: "문제", en: "problem" },
  { ko: '"진행', en: "procedure" },
  { ko: '"나아가다', en: "proceed" },
  { ko: '"진행', en: "process" },
  { ko: '"생산하다', en: "produce" },
  { ko: '"직업 공언', en: "profession" },
  { ko: "교수", en: "professor" },
  { ko: '"옆 얼굴', en: "profile" },
  { ko: '"이익', en: "profit" },
  { ko: '"깊은', en: "profound" },
  { ko: '"진행', en: "progress" },
  { ko: '"금하다', en: "prohibit" },
  { ko: '"두드러진', en: "prominent" },
  { ko: '"약속', en: "promise" },
  { ko: '"승진시키다 진행시키다', en: "promote" },
  { ko: '"재빠른', en: "prompt" },
  { ko: '"발음하다', en: "pronounce" },
  { ko: "증명", en: "proof" },
  { ko: '"고유의', en: "proper" },
  { ko: '"재산', en: "property" },
  { ko: '"비율', en: "proportion" },
  { ko: '"제의하다', en: "propose" },
  { ko: '"전망', en: "prospect" },
  { ko: "번영하다", en: "prosper" },
  { ko: '"보호하다', en: "protect" },
  { ko: "IG1s", en: "protein" },
  { ko: "단언하다", en: "protest" },
  { ko: '"뽐내는', en: "proud" },
  { ko: '"시험하다', en: "prove" },
  { ko: '"준비하다', en: "provide" },
  { ko: '"주', en: "province" },
  { ko: "화나게 하다", en: "provoke" },
  { ko: "심리학", en: "psychology" },
  { ko: "펍", en: "pub" },
  { ko: '"심리', en: "public" },
  { ko: '"발표 하다', en: "publish" },
  { ko: '"끌다', en: "pull" },
  { ko: "펌프스   댄스용 구두", en: "pump" },
  { ko: '"주먹질', en: "punch" },
  { ko: '"벌하다', en: "punish" },
  { ko: "흔히 국민학교 중학교 학생", en: "pupil" },
  { ko: "강아지", en: "puppy" },
  { ko: '"사다', en: "purchase" },
  { ko: '"순수한  깨끗한', en: "pure" },
  { ko: "자줏빛의  새빨간  제왕의", en: "purple" },
  { ko: "목적", en: "purpose" },
  { ko: '"쫓다', en: "pursue" },
  { ko: '"밀다', en: "push" },
  { ko: '"놓다', en: "put" },
  { ko: '"당황', en: "puzzle" },
  { ko: "자격을 부여하다", en: "qualify" },
  { ko: "질", en: "quality" },
  { ko: "양", en: "quantity" },
  { ko: "1", en: "quarter" },
  { ko: "여왕", en: "queen" },
  { ko: '"물음', en: "question" },
  { ko: "질문표", en: "questionnaire" },
  { ko: "빠른", en: "quick" },
  { ko: "조용한", en: "quiet" },
  { ko: '"(의무', en: "quit" },
  { ko: "아주", en: "quite" },
  { ko: "인용하다", en: "quote" },
  { ko: "집토끼", en: "rabbit" },
  { ko: "인종", en: "race" },
  { ko: "인종(상)의", en: "racial" },
  { ko: "격노", en: "rage" },
  { ko: "가로장", en: "rail" },
  { ko: "비", en: "rain" },
  { ko: "무지개", en: "rainbow" },
  { ko: "올리다", en: "raise" },
  { ko: "규합하다", en: "rally" },
  { ko: "닥치는 대로의", en: "random" },
  { ko: "줄", en: "range" },
  { ko: "열", en: "rank" },
  { ko: "빠른", en: "rapid" },
  { ko: "희귀한", en: "rare" },
  { ko: "쥐", en: "rat" },
  { ko: "율", en: "rate" },
  { ko: "오히려", en: "rather" },
  { ko: "합리적인", en: "rational" },
  { ko: "날것의", en: "raw" },
  { ko: "도착하다", en: "reach" },
  { ko: "반응을 나타내다", en: "react" },
  { ko: "읽다", en: "read" },
  { ko: "준비가 된", en: "ready" },
  { ko: "실재하는", en: "real" },
  { ko: "깨닫다", en: "realize" },
  { ko: "뒤", en: "rear" },
  { ko: "이성", en: "reason" },
  { ko: "반역자", en: "rebel" },
  { ko: "되부르다", en: "recall" },
  { ko: "수령", en: "receipt" },
  { ko: "받다", en: "receive" },
  { ko: "최근의", en: "recent" },
  { ko: "받음", en: "reception" },
  { ko: "조리법", en: "recipe" },
  { ko: "인정하다", en: "recognize" },
  { ko: "추천하다", en: "recommend" },
  { ko: "기록하다", en: "record" },
  { ko: "되찾다", en: "recover" },
  { ko: "신병", en: "recruit" },
  { ko: "재생 이용하다", en: "recycle" },
  { ko: "붉은", en: "red" },
  { ko: "줄이다", en: "reduce" },
  { ko: "조회시키다", en: "refer" },
  { ko: "정제정련하다", en: "refine" },
  { ko: "반사하다", en: "reflect" },
  { ko: "개정(개혁)하다", en: "reform" },
  { ko: "냉장고", en: "refrigerator" },
  { ko: "거절하다", en: "refuse" },
  { ko: "주목해서 보다", en: "regard" },
  { ko: "지방", en: "region" },
  { ko: "기록", en: "register" },
  { ko: "유감", en: "regret" },
  { ko: "규칙적인", en: "regular" },
  { ko: "규정하다", en: "regulate" },
  { ko: "보강하다", en: "reinforce" },
  { ko: "거절하다", en: "reject" },
  { ko: "이야기하다", en: "relate" },
  { ko: "친척", en: "relative" },
  { ko: "늦추다", en: "relax" },
  { ko: "도와주다", en: "release" },
  { ko: "관련된", en: "relevant" },
  { ko: "구출하다", en: "relieve" },
  { ko: "종교", en: "religion" },
  { ko: "마음이 내키지 않는", en: "reluctant" },
  { ko: "믿다", en: "rely" },
  { ko: "남다", en: "remain" },
  { ko: "깨닫다", en: "remark" },
  { ko: "치료", en: "remedy" },
  { ko: "기억하고 있다", en: "remember" },
  { ko: "생각나게 하다", en: "remind" },
  { ko: "먼", en: "remote" },
  { ko: "옮기다", en: "remove" },
  { ko: "지대", en: "rent" },
  { ko: "수선(수정)하다", en: "repair" },
  { ko: "반복하다", en: "repeat" },
  { ko: "되돌려 놓다", en: "replace" },
  { ko: "대답하다", en: "reply" },
  { ko: "보고", en: "report" },
  { ko: "표현(묘사)하다", en: "represent" },
  { ko: "공화국", en: "republic" },
  { ko: "평판", en: "reputation" },
  { ko: "부탁하다", en: "request" },
  { ko: "요구하다", en: "require" },
  { ko: "구하다", en: "rescue" },
  { ko: "연구", en: "research" },
  { ko: "닮다", en: "resemble" },
  { ko: "따로 두다", en: "reserve" },
  { ko: "거주하다", en: "reside" },
  { ko: "사임하다", en: "resign" },
  { ko: "저항하다", en: "resist" },
  { ko: "분해하다", en: "resolve" },
  { ko: "(자주)가다", en: "resort" },
  { ko: "자원", en: "resource" },
  { ko: "존경하다", en: "respect" },
  { ko: "각각의", en: "respective" },
  { ko: "대답하다", en: "respond" },
  { ko: "책임을 져야할", en: "responsible" },
  { ko: "휴식", en: "rest" },
  { ko: "요리점", en: "restaurant" },
  { ko: "반환하다", en: "restore" },
  { ko: "제지하다", en: "restrain" },
  { ko: "제한하다", en: "restrict" },
  { ko: "화장실", en: "restroom" },
  { ko: "결과", en: "result" },
  { ko: "다시 잡다", en: "resume" },
  { ko: "소매", en: "retail" },
  { ko: "보유하다", en: "retain" },
  { ko: "퇴직하다", en: "retire" },
  { ko: "후퇴", en: "retreat" },
  { ko: "돌아가다", en: "return" },
  { ko: "나타내다", en: "reveal" },
  { ko: "복수", en: "revenge" },
  { ko: "역", en: "reverse" },
  { ko: "재조사", en: "review" },
  { ko: "교정하다", en: "revise" },
  { ko: "소생하다", en: "revive" },
  { ko: "혁명", en: "revolution" },
  { ko: "보수", en: "reward" },
  { ko: "율동", en: "rhythm" },
  { ko: "쌀", en: "rice" },
  { ko: "부자인", en: "rich" },
  { ko: "면하게하다", en: "rid" },
  { ko: "타다", en: "ride" },
  { ko: "어리석은", en: "ridiculous" },
  { ko: "올바른", en: "right" },
  { ko: "고리", en: "ring" },
  { ko: '"폭동', en: "riot" },
  { ko: "올리다", en: "rise" },
  { ko: "위험 걸다", en: "risk" },
  { ko: "경쟁자 경쟁하는 경쟁하다", en: "rival" },
  { ko: "강", en: "river" },
  { ko: "길", en: "road" },
  { ko: "으르렁거리다 으르렁소리", en: "roar" },
  { ko: "불에 쬐어 굽다 불고기 구운", en: "roast" },
  { ko: '"강탈하다', en: "rob" },
  { ko: "바위", en: "rock" },
  { ko: "막대", en: "rod" },
  { ko: "(배우의)역", en: "role" },
  { ko: "구르다", en: "roll" },
  { ko: "전기소설적인", en: "romantic" },
  { ko: "지붕", en: "roof" },
  { ko: "방", en: "room" },
  { ko: "뿌리", en: "root" },
  { ko: "새끼", en: "rope" },
  { ko: "썩다", en: "rot" },
  { ko: "거친", en: "rough" },
  { ko: "둥근 원 돌아서", en: "round" },
  { ko: "길", en: "route" },
  { ko: "정해진 일", en: "routine" },
  { ko: "줄", en: "row" },
  { ko: "왕의", en: "royal" },
  { ko: "마찰하다", en: "rub" },
  { ko: "맛사지사", en: "rubber" },
  { ko: "버릇없는", en: "rude" },
  { ko: "파멸", en: "ruin" },
  { ko: "규칙", en: "rule" },
  { ko: "소문", en: "rumor" },
  { ko: "달리다", en: "run" },
  { ko: "시골의", en: "rural" },
  { ko: "돌진하다", en: "rush" },
  { ko: "마대", en: "sack" },
  { ko: "신성한", en: "sacred" },
  { ko: "희생", en: "sacrifice" },
  { ko: "슬픈", en: "sad" },
  { ko: "안전한", en: "safe" },
  { ko: "돛", en: "sail" },
  { ko: "봉급 봉급을 주다", en: "salary" },
  { ko: "판매", en: "sale" },
  { ko: "객실", en: "salon" },
  { ko: "소금", en: "salt" },
  { ko: "같은", en: "same" },
  { ko: "모래사장", en: "sand" },
  { ko: "위성", en: "satellite" },
  { ko: "만족시키다", en: "satisfy" },
  { ko: "위험에서 구하다", en: "save" },
  { ko: "말하다", en: "say" },
  { ko: "비늘(모양의 것)", en: "scale" },
  { ko: "시의 운율을살피다", en: "scan" },
  { ko: "추문", en: "scandal" },
  { ko: "부족한", en: "scarce" },
  { ko: "위협하다", en: "scare" },
  { ko: "뿔뿔이 흩어 버리다", en: "scatter" },
  { ko: "장면", en: "scene" },
  { ko: "계획", en: "scheme" },
  { ko: "학자", en: "scholar" },
  { ko: "학교", en: "school" },
  { ko: "과학", en: "science" },
  { ko: "가위", en: "scissors" },
  { ko: "꾸짖다 잔소리 심한 사람", en: "scold" },
  { ko: "범위", en: "scope" },
  { ko: "득점", en: "score" },
  { ko: "기다", en: "scramble" },
  { ko: '"할퀴다', en: "scratch" },
  { ko: "비명을 지르다", en: "scream" },
  { ko: "병풍", en: "screen" },
  { ko: "나사", en: "screw" },
  { ko: "(관목의)숲", en: "scrub" },
  { ko: "조각 조각하다", en: "sculpture" },
  { ko: "바다", en: "sea" },
  { ko: "인장", en: "seal" },
  { ko: "찾다", en: "search" },
  { ko: "계절", en: "season" },
  { ko: "좌석", en: "seat" },
  { ko: "비밀의", en: "secret" },
  { ko: "비서", en: "secretary" },
  { ko: "부채꼴", en: "sector" },
  { ko: "안전한", en: "secure" },
  { ko: "보다", en: "see" },
  { ko: "씨앗", en: "seed" },
  { ko: "찾다", en: "seek" },
  { ko: "-으로 보이다", en: "seem" },
  { ko: "붙잡다", en: "seize" },
  { ko: "고르다", en: "select" },
  { ko: "자기", en: "self" },
  { ko: "팔다", en: "sell" },
  { ko: "보내다", en: "send" },
  { ko: "연상의", en: "senior" },
  { ko: "감각", en: "sensation" },
  { ko: "감각", en: "sense" },
  { ko: "분별있는", en: "sensible" },
  { ko: "문장", en: "sentence" },
  { ko: "정서", en: "sentiment" },
  { ko: "분리된", en: "separate" },
  { ko: "연속", en: "sequence" },
  { ko: "연속", en: "series" },
  { ko: "진지한", en: "serious" },
  { ko: "섬기다", en: "serve" },
  { ko: "개회", en: "session" },
  { ko: "등받이가 높은 긴 의자 놓다", en: "settle" },
  { ko: "수개의", en: "several" },
  { ko: "호된", en: "severe" },
  { ko: "꿰매다", en: "sew" },
  { ko: "성", en: "sex" },
  { ko: "그늘", en: "shade" },
  { ko: "그림자", en: "shadow" },
  { ko: "흔들어 움직이다", en: "shake" },
  { ko: "au-하겠다", en: "shall" },
  { ko: "얕은 얕은 곳 얕아지다", en: "shallow" },
  { ko: "부끄럼", en: "shame" },
  { ko: "모양", en: "shape" },
  { ko: "몫", en: "share" },
  { ko: "날카로운", en: "sharp" },
  { ko: "깎다", en: "shave" },
  { ko: "그녀는", en: "she" },
  { ko: "양", en: "sheep" },
  { ko: "깔천", en: "sheet" },
  { ko: "선반", en: "shelf" },
  { ko: "겉껍질", en: "shell" },
  { ko: "피난처", en: "shelter" },
  { ko: "방패", en: "shield" },
  { ko: "옮기다", en: "shift" },
  { ko: "빛나다", en: "shine" },
  { ko: "배", en: "ship" },
  { ko: "격돌", en: "shock" },
  { ko: "구두", en: "shoe" },
  { ko: "쏘다", en: "shoot" },
  { ko: "상점", en: "shop" },
  { ko: "물가", en: "shore" },
  { ko: "짧은", en: "short" },
  { ko: "aushall의 과거", en: "should" },
  { ko: "어깨", en: "shoulder" },
  { ko: "외치다", en: "shout" },
  { ko: "보이다", en: "show" },
  { ko: "소나기 빗발치듯 퍼붓다(쏟다)", en: "shower" },
  { ko: "줄어들다", en: "shrink" },
  { ko: "닫다", en: "shut" },
  { ko: "수줍은", en: "shy" },
  { ko: "병난", en: "sick" },
  { ko: "쪽", en: "side" },
  { ko: "한숨", en: "sigh" },
  { ko: "광경", en: "sight" },
  { ko: "부호", en: "sign" },
  { ko: "중요한", en: "significant" },
  { ko: "조용한", en: "silent" },
  { ko: "비단", en: "silk" },
  { ko: "어리석은 바보", en: "silly" },
  { ko: "은", en: "silver" },
  { ko: "유사한", en: "similar" },
  { ko: "단일의", en: "simple" },
  { ko: "흉내내다", en: "simulate" },
  { ko: "동시에 일어나는(존재하는)", en: "simultaneous" },
  { ko: "사인", en: "sin" },
  { ko: "-이래", en: "since" },
  { ko: "노래하다", en: "sing" },
  { ko: "단 하나의", en: "single" },
  { ko: "가라앉다", en: "sink" },
  { ko: "여자형제", en: "sister" },
  { ko: "앉다", en: "sit" },
  { ko: "부지", en: "site" },
  { ko: "장소", en: "situation" },
  { ko: "크기", en: "size" },
  { ko: "숙련", en: "skill" },
  { ko: "피부", en: "skin" },
  { ko: "도약", en: "skip" },
  { ko: "스커어트", en: "skirt" },
  { ko: "하늘", en: "sky" },
  { ko: "도살", en: "slaughter" },
  { ko: "노예 노예처럼 일하다", en: "slave" },
  { ko: "잠자다", en: "sleep" },
  { ko: "얇은조각", en: "slice" },
  { ko: "미끄러지다", en: "slide" },
  { ko: "약간의", en: "slight" },
  { ko: "호리호리한", en: "slim" },
  { ko: "(때가)어느덧 지나가다", en: "slip" },
  { ko: "비탈", en: "slope" },
  { ko: "느린", en: "slow" },
  { ko: "작은 작은 부분 적게", en: "small" },
  { ko: "재치있는", en: "smart" },
  { ko: "박살내다", en: "smash" },
  { ko: "냄새", en: "smell" },
  { ko: "미소짓다 미소", en: "smile" },
  { ko: "연기", en: "smoke" },
  { ko: "매끄러운", en: "smooth" },
  { ko: "뱀", en: "snake" },
  { ko: "덥석 물다", en: "snap" },
  { ko: "몰래 움직이다", en: "sneak" },
  { ko: "코를 킁킁거리다", en: "sniff" },
  { ko: "눈 눈이 내리다", en: "snow" },
  { ko: "그와 같이", en: "so" },
  { ko: "담그다", en: "soak" },
  { ko: "비누 비누로 씻다", en: "soap" },
  { ko: "축구", en: "soccer" },
  { ko: "사회의", en: "social" },
  { ko: "사회", en: "society" },
  { ko: "사회학", en: "sociology" },
  { ko: "짧은 양말", en: "sock" },
  { ko: "부드러운", en: "soft" },
  { ko: "소프트웨어", en: "software" },
  { ko: "흙", en: "soil" },
  { ko: "군인", en: "soldier" },
  { ko: "유일한 발바닥", en: "sole" },
  { ko: "고체의", en: "solid" },
  { ko: "독주", en: "solo" },
  { ko: "해결하다", en: "solve" },
  { ko: "얼만가의", en: "some" },
  { ko: "약간", en: "somewhat" },
  { ko: "아들", en: "son" },
  { ko: "노래", en: "song" },
  { ko: "얼마 안 가서", en: "soon" },
  { ko: "물정에 닳고 닳은", en: "sophisticated" },
  { ko: "슬픈", en: "sore" },
  { ko: "가엾은", en: "sorry" },
  { ko: "종류", en: "sort" },
  { ko: "혼", en: "soul" },
  { ko: "소리", en: "sound" },
  { ko: "시큼한 시어지다 시큼한 것", en: "sour" },
  { ko: "원천", en: "source" },
  { ko: "남쪽 남쪽의 남으로", en: "south" },
  { ko: "공간", en: "space" },
  { ko: "한 뼘", en: "span" },
  { ko: "여분의", en: "spare" },
  { ko: "불꽃", en: "spark" },
  { ko: "이야기하다", en: "speak" },
  { ko: "특별한", en: "special" },
  { ko: "종", en: "species" },
  { ko: "특정한", en: "specific" },
  { ko: "광경", en: "spectacle" },
  { ko: "스펙트럼", en: "spectrum" },
  { ko: "연설", en: "speech" },
  { ko: "속도", en: "speed" },
  { ko: "철자하다", en: "spell" },
  { ko: "소비하다", en: "spend" },
  { ko: "구", en: "sphere" },
  { ko: "엎지르다", en: "spill" },
  { ko: "잣다", en: "spin" },
  { ko: "정신", en: "spirit" },
  { ko: "침을 뱉다", en: "spit" },
  { ko: "악의", en: "spite" },
  { ko: "튀기다", en: "splash" },
  { ko: "쪼개다", en: "split" },
  { ko: "망쳐놓다", en: "spoil" },
  { ko: "숟가락", en: "spoon" },
  { ko: "장소", en: "spot" },
  { ko: "배우자", en: "spouse" },
  { ko: "펴다", en: "spread" },
  { ko: "정사각형의", en: "square" },
  { ko: "압착하다", en: "squeeze" },
  { ko: "안정된", en: "stable" },
  { ko: "낟가리", en: "stack" },
  { ko: "무대", en: "stage" },
  { ko: "더럽히다", en: "stain" },
  { ko: "계단", en: "stairs" },
  { ko: "도장", en: "stamp" },
  { ko: "서다", en: "stand" },
  { ko: "표준", en: "standard" },
  { ko: "응시하다", en: "stare" },
  { ko: "시작하다", en: "start" },
  { ko: "굶어 죽다", en: "starve" },
  { ko: "상태", en: "state" },
  { ko: "역", en: "station" },
  { ko: "통계의 통계량", en: "statistic" },
  { ko: "조상", en: "statue" },
  { ko: "신분", en: "status" },
  { ko: "머무르다", en: "stay" },
  { ko: "확고한", en: "steady" },
  { ko: "훔치다", en: "steal" },
  { ko: "증기", en: "steam" },
  { ko: "강철", en: "steel" },
  { ko: "가파른 -에 담그다 잠기다 담그기", en: "steep" },
  { ko: "줄기", en: "stem" },
  { ko: "걷다", en: "step" },
  { ko: "나무토막", en: "stick" },
  { ko: "굳은", en: "stiff" },
  { ko: "소리가 없는 아직(도)", en: "still" },
  { ko: "자극하다", en: "stimulate" },
  { ko: "휘젓다", en: "stir" },
  { ko: "한 바늘", en: "stitch" },
  { ko: "줄기", en: "stock" },
  { ko: "위", en: "stomach" },
  { ko: "돌", en: "stone" },
  { ko: "멈추다", en: "stop" },
  { ko: "가게", en: "store" },
  { ko: "폭풍", en: "storm" },
  { ko: "층", en: "story" },
  { ko: "stave의 과거(분사)", en: "stove" },
  { ko: "곧은", en: "straight" },
  { ko: "잡아당기다", en: "strain" },
  { ko: "이상한", en: "strange" },
  { ko: "용병학", en: "strategy" },
  { ko: "짚", en: "straw" },
  { ko: "딸기", en: "strawberry" },
  { ko: "시내", en: "stream" },
  { ko: "거리", en: "street" },
  { ko: "압박", en: "stress" },
  { ko: "뻗치다", en: "stretch" },
  { ko: "엄중한", en: "strict" },
  { ko: "치다", en: "strike" },
  { ko: "끈", en: "string" },
  { ko: "벗기다", en: "strip" },
  { ko: "줄무늬", en: "stripe" },
  { ko: "한번치기", en: "stroke" },
  { ko: "강한", en: "strong" },
  { ko: "구조", en: "structure" },
  { ko: "버둥거리다", en: "struggle" },
  { ko: "학생", en: "student" },
  { ko: "학문", en: "study" },
  { ko: "재료", en: "stuff" },
  { ko: "복종시키다", en: "subject" },
  { ko: "주관의", en: "subjective" },
  { ko: "잠수함", en: "submarine" },
  { ko: "복종시키다", en: "submit" },
  { ko: "서명승락하다", en: "subscribe" },
  { ko: "물질", en: "substance" },
  { ko: "실체의", en: "substantial" },
  { ko: "대용하다 대신하다 대리(인)", en: "substitute" },
  { ko: "미묘한", en: "subtle" },
  { ko: "교외", en: "suburb" },
  { ko: "지하도", en: "subway" },
  { ko: "성공하다", en: "succeed" },
  { ko: "이러한", en: "such" },
  { ko: "빨다", en: "suck" },
  { ko: "별안간의", en: "sudden" },
  { ko: "경험하다", en: "suffer" },
  { ko: "충분한", en: "sufficient" },
  { ko: "설탕", en: "sugar" },
  { ko: "암시하다", en: "suggest" },
  { ko: "자살 자살하다", en: "suicide" },
  { ko: "소송", en: "suit" },
  { ko: "수행원", en: "suite" },
  { ko: "총계", en: "sum" },
  { ko: "요약", en: "summary" },
  { ko: "꼭대기", en: "summit" },
  { ko: "태양", en: "sun" },
  { ko: "임시고용배우", en: "super" },
  { ko: "장려한", en: "superb" },
  { ko: "뛰어난", en: "superior" },
  { ko: "감독하다", en: "supervise" },
  { ko: "저녁식사", en: "supper" },
  { ko: "부록", en: "supplement" },
  { ko: "공급하다", en: "supply" },
  { ko: "지탱하다", en: "support" },
  { ko: "상상하다", en: "suppose" },
  { ko: '"확신하는', en: "sure" },
  { ko: "표면", en: "surface" },
  { ko: "외과", en: "surgery" },
  { ko: "놀람", en: "surprise" },
  { ko: "넘겨주다", en: "surrender" },
  { ko: "에워싸다", en: "surround" },
  { ko: "둘러보다", en: "survey" },
  { ko: "살아 남다", en: "survive" },
  { ko: "짐작하다", en: "suspect" },
  { ko: "매달다", en: "suspend" },
  { ko: "떠받치다", en: "sustain" },
  { ko: "삼키다", en: "swallow" },
  { ko: "맹세하다", en: "swear" },
  { ko: "땀", en: "sweat" },
  { ko: "청소하다", en: "sweep" },
  { ko: "단", en: "sweet" },
  { ko: "부풀다", en: "swell" },
  { ko: "빠른", en: "swift" },
  { ko: "헤엄치다", en: "swim" },
  { ko: "흔들리다", en: "swing" },
  { ko: "회초리", en: "switch" },
  { ko: "상징", en: "symbol" },
  { ko: "동정", en: "sympathy" },
  { ko: "교향곡", en: "symphony" },
  { ko: "조짐", en: "symptom" },
  { ko: "조직", en: "system" },
  { ko: "테이블", en: "table" },
  { ko: "고패", en: "tackle" },
  { ko: "손잡이가죽", en: "tag" },
  { ko: "꼬리", en: "tail" },
  { ko: "잡다", en: "take" },
  { ko: "이야기", en: "tale" },
  { ko: "재주", en: "talent" },
  { ko: "말하다", en: "talk" },
  { ko: "키큰", en: "tall" },
  { ko: "가볍게 치기", en: "tap" },
  { ko: "테이프", en: "tape" },
  { ko: "과녁", en: "target" },
  { ko: "일", en: "task" },
  { ko: "맛", en: "taste" },
  { ko: "귀영나팔", en: "tattoo" },
  { ko: "세금", en: "tax" },
  { ko: "차", en: "tea" },
  { ko: "가르치다", en: "teach" },
  { ko: "눈물", en: "tear" },
  { ko: "괴롭히다", en: "tease" },
  { ko: "슬픔", en: "teen" },
  { ko: "10대", en: "teenage" },
  { ko: "전신", en: "telegraph" },
  { ko: "전화", en: "telephone" },
  { ko: "말하다", en: "tell" },
  { ko: "온도", en: "temperature" },
  { ko: "관자놀이", en: "temple" },
  { ko: "일시적인", en: "temporary" },
  { ko: "유혹하다", en: "tempt" },
  { ko: "차지인", en: "tenant" },
  { ko: "(-의)경향이 있다", en: "tend" },
  { ko: "제공", en: "tender" },
  { ko: "시제", en: "tense" },
  { ko: "기간", en: "term" },
  { ko: "종점의", en: "terminal" },
  { ko: "끝내다", en: "terminate" },
  { ko: "계단모양의 뜰(광장)", en: "terrace" },
  { ko: "무시무시한", en: "terrible" },
  { ko: "무서운", en: "terrific" },
  { ko: "영토", en: "territory" },
  { ko: "시험", en: "test" },
  { ko: "증명하다", en: "testify" },
  { ko: "원문", en: "text" },
  { ko: "교과서", en: "textbook" },
  { ko: "-보다도", en: "than" },
  { ko: "감사하다 감사", en: "thank" },
  { ko: "저", en: "that" },
  { ko: "art.저", en: "the" },
  { ko: "=theatre 극장", en: "theater" },
  { ko: "논제", en: "theme" },
  { ko: "그때", en: "then" },
  { ko: "이론", en: "theory" },
  { ko: "치료법", en: "therapy" },
  { ko: "거기에", en: "there" },
  { ko: "그런 까닭에", en: "therefore" },
  { ko: "그들", en: "they" },
  { ko: "두꺼운", en: "thick" },
  { ko: "도둑", en: "thief" },
  { ko: "얇은", en: "thin" },
  { ko: "물건", en: "thing" },
  { ko: "생각하다", en: "think" },
  { ko: "갈증", en: "thirst" },
  { ko: "이", en: "this" },
  { ko: "완전한", en: "thorough" },
  { ko: "-임에도 불구하고 그러나", en: "though" },
  { ko: "천", en: "thousand" },
  { ko: "실", en: "thread" },
  { ko: "협박", en: "threat" },
  { ko: "오싹하다 오싹함", en: "thrill" },
  { ko: "목", en: "throat" },
  { ko: "(-을)통하여 통하여 직통의", en: "through" },
  { ko: "던지다", en: "throw" },
  { ko: "엄지손가락 엄지손가락으로 만지다", en: "thumb" },
  { ko: "이렇게", en: "thus" },
  { ko: "시계소리", en: "tick" },
  { ko: "조수", en: "tide" },
  { ko: "말쑥한", en: "tidy" },
  { ko: "매다", en: "tie" },
  { ko: "호랑이", en: "tiger" },
  { ko: "단단한", en: "tight" },
  { ko: "-까지", en: "till" },
  { ko: "재목", en: "timber" },
  { ko: "때", en: "time" },
  { ko: "주석", en: "tin" },
  { ko: "자그마한", en: "tiny" },
  { ko: "끝", en: "tip" },
  { ko: "피로하게 하다", en: "tire" },
  { ko: "조직", en: "tissue" },
  { ko: "표제", en: "title" },
  { ko: "-로", en: "to" },
  { ko: "담배", en: "tobacco" },
  { ko: "오늘은", en: "today" },
  { ko: "발가락", en: "toe" },
  { ko: "같이", en: "together" },
  { ko: "화장실", en: "toilet" },
  { ko: "내일(은)", en: "tomorrow" },
  { ko: "음조", en: "tone" },
  { ko: "혀", en: "tongue" },
  { ko: "오늘밤에 오늘밤", en: "tonight" },
  { ko: "(-도)또한", en: "too" },
  { ko: "사용세", en: "tool" },
  { ko: "이", en: "tooth" },
  { ko: "정상", en: "top" },
  { ko: "고문", en: "torture" },
  { ko: "던지다", en: "toss" },
  { ko: "총계 전체의 합계하다", en: "total" },
  { ko: "닿다", en: "touch" },
  { ko: "단단한", en: "tough" },
  { ko: "일주", en: "tour" },
  { ko: "-쪽으로", en: "toward" },
  { ko: "탑", en: "tower" },
  { ko: "읍", en: "town" },
  { ko: "독의", en: "toxic" },
  { ko: "장난감 장난하다", en: "toy" },
  { ko: "발자국", en: "trace" },
  { ko: "매매", en: "trade" },
  { ko: "전설", en: "tradition" },
  { ko: "교통", en: "traffic" },
  { ko: "비극의", en: "tragic" },
  { ko: "질질 끌다", en: "trail" },
  { ko: "기차", en: "train" },
  { ko: "처리하다", en: "transact" },
  { ko: "옮기다", en: "transfer" },
  { ko: '"변형(변용', en: "transform" },
  { ko: "변천", en: "transition" },
  { ko: "번역하다", en: "translate" },
  { ko: "보내다", en: "transmit" },
  { ko: "수송(운송)하다", en: "transport" },
  { ko: "덫", en: "trap" },
  { ko: "여행하다", en: "travel" },
  { ko: "쟁반", en: "tray" },
  { ko: "보물", en: "treasure" },
  { ko: "대우하다", en: "treat" },
  { ko: "조약", en: "treaty" },
  { ko: "나무", en: "tree" },
  { ko: "무서운", en: "tremendous" },
  { ko: "방향", en: "trend" },
  { ko: "시험", en: "trial" },
  { ko: "각형", en: "triangle" },
  { ko: "종족", en: "tribe" },
  { ko: "책략", en: "trick" },
  { ko: "방아쇠 재빠른", en: "trigger" },
  { ko: "산뜻한 정돈하다", en: "trim" },
  { ko: "여행", en: "trip" },
  { ko: "승리", en: "triumph" },
  { ko: "대", en: "troop" },
  { ko: "전리품", en: "trophy" },
  { ko: "고생", en: "trouble" },
  { ko: "즈봉", en: "trouser" },
  { ko: "진실", en: "true" },
  { ko: "줄기", en: "trunk" },
  { ko: "신용", en: "trust" },
  { ko: "진리", en: "truth" },
  { ko: "시험해보다", en: "try" },
  { ko: "관", en: "tube" },
  { ko: "곡", en: "tune" },
  { ko: "터널", en: "tunnel" },
  { ko: "돌리다", en: "turn" },
  { ko: "전복", en: "turnover" },
  { ko: "가정교사", en: "tutor" },
  { ko: "두 번", en: "twice" },
  { ko: "쌍동이", en: "twin" },
  { ko: "꼬이다", en: "twist" },
  { ko: "형", en: "type" },
  { ko: "전형적인", en: "typical" },
  { ko: "추한", en: "ugly" },
  { ko: "최후의", en: "ultimate" },
  { ko: "우산", en: "umbrella" },
  { ko: "아저씨", en: "uncle" },
  { ko: "-아래에", en: "under" },
  { ko: "(영향 등을)받다", en: "undergo" },
  { ko: "-의 밑에 있다", en: "underlie" },
  { ko: "-밑을 파다", en: "undermine" },
  { ko: "이해하다", en: "understand" },
  { ko: "떠맡다", en: "undertake" },
  { ko: "한결같은", en: "uniform" },
  { ko: "하나로 하다", en: "unify" },
  { ko: "결합", en: "union" },
  { ko: "유일무이한", en: "unique" },
  { ko: "단위", en: "unit" },
  { ko: "결합하다", en: "unite" },
  { ko: "우주", en: "universe" },
  { ko: "종합대학(교) 대학의(에 관계 있는)", en: "university" },
  { ko: "-하지 않으면", en: "unless" },
  { ko: "-까지", en: "until" },
  { ko: "위로", en: "up" },
  { ko: "새롭게 하다 최신정보", en: "update" },
  { ko: "-의 위에", en: "upon" },
  { ko: "위쪽의", en: "upper" },
  { ko: "뒤집어 엎다", en: "upset" },
  { ko: "위로 향한", en: "upward" },
  { ko: "도시의", en: "urban" },
  { ko: "몰아대다", en: "urge" },
  { ko: "긴급한", en: "urgent" },
  { ko: "쓰다", en: "use" },
  { ko: "평소의", en: "usual" },
  { ko: "-을 이용하다", en: "utilize" },
  { ko: "전적인", en: "utter" },
  { ko: "휴가", en: "vacation" },
  { ko: "진공", en: "vacuum" },
  { ko: "막연한", en: "vague" },
  { ko: "유효한", en: "valid" },
  { ko: "골짜기", en: "valley" },
  { ko: "가치", en: "value" },
  { ko: "유개트럭", en: "van" },
  { ko: "자취를 감추다", en: "vanish" },
  { ko: "가지가지의", en: "various" },
  { ko: "바꾸다", en: "vary" },
  { ko: '"광대한', en: "vast" },
  { ko: '"식물  야채', en: "vegetable" },
  { ko: '"운반 기구', en: "vehicle" },
  { ko: "모험", en: "venture" },
  { ko: '"말의', en: "verbal" },
  { ko: '"시의 한 줄', en: "verse" },
  { ko: '"번역', en: "version" },
  { ko: '"…대', en: "versus" },
  { ko: '"수평면에 직각인', en: "vertical" },
  { ko: "매우", en: "very" },
  { ko: "그릇", en: "vessel" },
  { ko: '"노련가', en: "veteran" },
  { ko: "수의사", en: "veterinarian" },
  { ko: '"…을 거쳐', en: "via" },
  { ko: '"악덕', en: "vice" },
  { ko: '"희생', en: "victim" },
  { ko: '"승리', en: "victory" },
  { ko: '"봄', en: "view" },
  { ko: '"정력적인', en: "vigorous" },
  { ko: '"마을', en: "village" },
  { ko: '"격렬한', en: "violent" },
  { ko: '"처녀', en: "virgin" },
  { ko: '"사실상의', en: "virtual" },
  { ko: '"덕', en: "virtue" },
  { ko: '"눈에 보이는', en: "visible" },
  { ko: '"방문하다', en: "visit" },
  { ko: '"시각의', en: "visual" },
  { ko: '"생명의', en: "vital" },
  { ko: '"발랄한', en: "vivid" },
  { ko: '"어휘', en: "vocabulary" },
  { ko: '"천직', en: "vocation" },
  { ko: '"목소리', en: "voice" },
  { ko: "책  권", en: "volume" },
  { ko: '"자발적인', en: "voluntary" },
  { ko: '"찬부 표시', en: "vote" },
  { ko: "여행", en: "voyage" },
  { ko: "임금", en: "wage" },
  { ko: "짐마차", en: "wagon" },
  { ko: "기다리다", en: "wait" },
  { ko: "잠깨다", en: "wake" },
  { ko: "걷다", en: "walk" },
  { ko: "벽", en: "wall" },
  { ko: "헤매다", en: "wander" },
  { ko: "결핍", en: "want" },
  { ko: "전쟁", en: "war" },
  { ko: "창고", en: "warehouse" },
  { ko: "따뜻한", en: "warm" },
  { ko: "경고하다", en: "warn" },
  { ko: "보증하다 보증", en: "warrant" },
  { ko: "병사", en: "warrior" },
  { ko: "씻다", en: "wash" },
  { ko: "낭비하다", en: "waste" },
  { ko: "손목시계", en: "watch" },
  { ko: "물", en: "water" },
  { ko: "수박", en: "watermelon" },
  { ko: "물결", en: "wave" },
  { ko: "길", en: "way" },
  { ko: "우리가", en: "we" },
  { ko: "약한", en: "weak" },
  { ko: "재산", en: "wealth" },
  { ko: "무기", en: "weapon" },
  { ko: "입다", en: "wear" },
  { ko: "날씨", en: "weather" },
  { ko: "짜다", en: "weave" },
  { ko: "혼례", en: "wedding" },
  { ko: "잡초 잡초를 뽑다", en: "weed" },
  { ko: "주", en: "week" },
  { ko: "주말 주말의 주말을 지내다", en: "weekend" },
  { ko: "무게를 달다", en: "weigh" },
  { ko: "무게", en: "weight" },
  { ko: "불가사의한", en: "weird" },
  { ko: "환영 환영받는", en: "welcome" },
  { ko: "행복", en: "welfare" },
  { ko: "잘", en: "well" },
  { ko: "서쪽", en: "west" },
  { ko: "축축한", en: "wet" },
  { ko: "고래", en: "whale" },
  { ko: "무엇 무슨", en: "what" },
  { ko: "밀", en: "wheat" },
  { ko: "바퀴", en: "wheel" },
  { ko: "언제", en: "when" },
  { ko: "어디에 (-하는)곳에 pr.어디 (문제의)장소", en: "where" },
  { ko: "cnj.(-인)까닭에", en: "whereas" },
  { ko: "-인지 어떤지", en: "whether" },
  { ko: "어느 쪽", en: "which" },
  { ko: "동안 -하는 동안", en: "while" },
  { ko: "채찍 채찍질하다", en: "whip" },
  { ko: "속삭이다", en: "whisper" },
  { ko: "휘파람", en: "whistle" },
  { ko: "흰", en: "white" },
  { ko: "누구", en: "who" },
  { ko: "전체의", en: "whole" },
  { ko: "왜", en: "why" },
  { ko: "사악한", en: "wicked" },
  { ko: "폭넓은", en: "wide" },
  { ko: "널리 보급되어 있는", en: "widespread" },
  { ko: "미망인", en: "widow" },
  { ko: "아내", en: "wife" },
  { ko: "야생의", en: "wild" },
  { ko: "의지", en: "will" },
  { ko: "이기다", en: "win" },
  { ko: "바람", en: "wind" },
  { ko: "창", en: "window" },
  { ko: "날개", en: "wing" },
  { ko: "닦다", en: "wipe" },
  { ko: "철사", en: "wire" },
  { ko: "슬기로운", en: "wise" },
  { ko: "바라다", en: "wish" },
  { ko: "기지", en: "wit" },
  { ko: "함께", en: "with" },
  { ko: "물러나다", en: "withdraw" },
  { ko: "prop.-의 안쪽에 안으로 내부", en: "within" },
  { ko: "prop.-없이 밖은", en: "without" },
  { ko: "증언", en: "witness" },
  { ko: "부인", en: "woman" },
  { ko: "경이", en: "wonder" },
  { ko: "숲", en: "wood" },
  { ko: "양모", en: "wool" },
  { ko: "낱말", en: "word" },
  { ko: "일", en: "work" },
  { ko: "세계", en: "world" },
  { ko: "근심하다", en: "worry" },
  { ko: "숭배", en: "worship" },
  { ko: "가치가 있는 가치", en: "worth" },
  { ko: "auwill의 과거", en: "would" },
  { ko: "부상", en: "wound" },
  { ko: "싸다", en: "wrap" },
  { ko: "난파", en: "wreck" },
  { ko: "쓰다", en: "write" },
  { ko: "나쁜", en: "wrong" },
  { ko: "연", en: "year" },
  { ko: "고함치다", en: "yell" },
  { ko: "황색의 황색", en: "yellow" },
  { ko: "예", en: "yes" },
  { ko: "어제", en: "yesterday" },
  { ko: "아직", en: "yet" },
  { ko: "산출하다", en: "yield" },
  { ko: "당신", en: "you" },
  { ko: "젊은", en: "young" },
  { ko: "얼룩말", en: "zebra" },
  { ko: "대", en: "zone" },
  { ko: "동물원", en: "zoo" },
]
